//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class P_0_0FinalDataAll : XPLiteObject
    {
        string fBillingDocument;
        [Size(255)]
        [Persistent(@"Billing Document")]
        public string BillingDocument
        {
            get { return fBillingDocument; }
            set { SetPropertyValue<string>("BillingDocument", ref fBillingDocument, value); }
        }
        double fSalesEh;
        [Persistent(@"Sales Eh")]
        public double SalesEh
        {
            get { return fSalesEh; }
            set { SetPropertyValue<double>("SalesEh", ref fSalesEh, value); }
        }
        double fVolume14;
        [Persistent(@"Volume 14")]
        public double Volume14
        {
            get { return fVolume14; }
            set { SetPropertyValue<double>("Volume14", ref fVolume14, value); }
        }
        double fVolume13;
        [Persistent(@"Volume 13")]
        public double Volume13
        {
            get { return fVolume13; }
            set { SetPropertyValue<double>("Volume13", ref fVolume13, value); }
        }
        double fValue14;
        [Persistent(@"Value 14")]
        public double Value14
        {
            get { return fValue14; }
            set { SetPropertyValue<double>("Value14", ref fValue14, value); }
        }
        double fValue13;
        [Persistent(@"Value 13")]
        public double Value13
        {
            get { return fValue13; }
            set { SetPropertyValue<double>("Value13", ref fValue13, value); }
        }
        double fValue12;
        [Persistent(@"Value 12")]
        public double Value12
        {
            get { return fValue12; }
            set { SetPropertyValue<double>("Value12", ref fValue12, value); }
        }
        double fValue11;
        [Persistent(@"Value 11")]
        public double Value11
        {
            get { return fValue11; }
            set { SetPropertyValue<double>("Value11", ref fValue11, value); }
        }
        double fCases14;
        [Persistent(@"Cases 14")]
        public double Cases14
        {
            get { return fCases14; }
            set { SetPropertyValue<double>("Cases14", ref fCases14, value); }
        }
        double fCases13;
        [Persistent(@"Cases 13")]
        public double Cases13
        {
            get { return fCases13; }
            set { SetPropertyValue<double>("Cases13", ref fCases13, value); }
        }
        double fCases12;
        [Persistent(@"Cases 12")]
        public double Cases12
        {
            get { return fCases12; }
            set { SetPropertyValue<double>("Cases12", ref fCases12, value); }
        }
        double fCases11;
        [Persistent(@"Cases 11")]
        public double Cases11
        {
            get { return fCases11; }
            set { SetPropertyValue<double>("Cases11", ref fCases11, value); }
        }
        double fVolume;
        public double Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<double>("Volume", ref fVolume, value); }
        }
        double fNewCases;
        [Persistent(@"New Cases")]
        public double NewCases
        {
            get { return fNewCases; }
            set { SetPropertyValue<double>("NewCases", ref fNewCases, value); }
        }
        string fType;
        [Size(5)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>("Type", ref fType, value); }
        }
        double fCases;
        public double Cases
        {
            get { return fCases; }
            set { SetPropertyValue<double>("Cases", ref fCases, value); }
        }
        double fValue;
        public double Value
        {
            get { return fValue; }
            set { SetPropertyValue<double>("Value", ref fValue, value); }
        }
        double fPricePoint;
        [Persistent(@"Price Point")]
        public double PricePoint
        {
            get { return fPricePoint; }
            set { SetPropertyValue<double>("PricePoint", ref fPricePoint, value); }
        }
        string fMaterialType;
        [Size(255)]
        [Persistent(@"Material Type")]
        public string MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<string>("MaterialType", ref fMaterialType, value); }
        }
        double fPallet;
        public double Pallet
        {
            get { return fPallet; }
            set { SetPropertyValue<double>("Pallet", ref fPallet, value); }
        }
        double fConsumerprice_Piece;
        [Persistent(@"Consumer price /Piece")]
        public double Consumerprice_Piece
        {
            get { return fConsumerprice_Piece; }
            set { SetPropertyValue<double>("Consumerprice_Piece", ref fConsumerprice_Piece, value); }
        }
        string fConsumerprice_Carton;
        [Size(255)]
        [Persistent(@"Consumer price /Carton")]
        public string Consumerprice_Carton
        {
            get { return fConsumerprice_Carton; }
            set { SetPropertyValue<string>("Consumerprice_Carton", ref fConsumerprice_Carton, value); }
        }
        string fRouteNumbersystem;
        [Size(255)]
        [Persistent(@"Route Number  system")]
        public string RouteNumbersystem
        {
            get { return fRouteNumbersystem; }
            set { SetPropertyValue<string>("RouteNumbersystem", ref fRouteNumbersystem, value); }
        }
        string fGroup3;
        [Size(255)]
        [Persistent(@"Group 3")]
        public string Group3
        {
            get { return fGroup3; }
            set { SetPropertyValue<string>("Group3", ref fGroup3, value); }
        }
        string fGroup2;
        [Size(255)]
        [Persistent(@"Group 2")]
        public string Group2
        {
            get { return fGroup2; }
            set { SetPropertyValue<string>("Group2", ref fGroup2, value); }
        }
        string fGroup1;
        [Size(255)]
        [Persistent(@"Group 1")]
        public string Group1
        {
            get { return fGroup1; }
            set { SetPropertyValue<string>("Group1", ref fGroup1, value); }
        }
        string fSDNCode;
        [Size(255)]
        [Persistent(@"SDN Code")]
        public string SDNCode
        {
            get { return fSDNCode; }
            set { SetPropertyValue<string>("SDNCode", ref fSDNCode, value); }
        }
        string fSDN_Custtype;
        [Size(265)]
        [Persistent(@"SDN &Custtype")]
        public string SDN_Custtype
        {
            get { return fSDN_Custtype; }
            set { SetPropertyValue<string>("SDN_Custtype", ref fSDN_Custtype, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fCustomerType_STI;
        [Size(255)]
        [Persistent(@"Customer Type_STI")]
        public string CustomerType_STI
        {
            get { return fCustomerType_STI; }
            set { SetPropertyValue<string>("CustomerType_STI", ref fCustomerType_STI, value); }
        }
        double fWeekNCE;
        [Persistent(@"Week NCE")]
        public double WeekNCE
        {
            get { return fWeekNCE; }
            set { SetPropertyValue<double>("WeekNCE", ref fWeekNCE, value); }
        }
        double fTradePrice_Piece;
        [Persistent(@"Trade Price/Piece")]
        public double TradePrice_Piece
        {
            get { return fTradePrice_Piece; }
            set { SetPropertyValue<double>("TradePrice_Piece", ref fTradePrice_Piece, value); }
        }
        double fTradePrice_Carton;
        [Persistent(@"Trade Price/Carton")]
        public double TradePrice_Carton
        {
            get { return fTradePrice_Carton; }
            set { SetPropertyValue<double>("TradePrice_Carton", ref fTradePrice_Carton, value); }
        }
        string fPricePointrang;
        [Size(255)]
        [Persistent(@"Price Point rang")]
        public string PricePointrang
        {
            get { return fPricePointrang; }
            set { SetPropertyValue<string>("PricePointrang", ref fPricePointrang, value); }
        }
        string fPriceIncreas;
        [Size(255)]
        [Persistent(@"Price Increas")]
        public string PriceIncreas
        {
            get { return fPriceIncreas; }
            set { SetPropertyValue<string>("PriceIncreas", ref fPriceIncreas, value); }
        }
        double fNewQu;
        [Persistent(@"New Qu")]
        public double NewQu
        {
            get { return fNewQu; }
            set { SetPropertyValue<double>("NewQu", ref fNewQu, value); }
        }
        double fVolumPice;
        [Persistent(@"Volum Pice")]
        public double VolumPice
        {
            get { return fVolumPice; }
            set { SetPropertyValue<double>("VolumPice", ref fVolumPice, value); }
        }
        double fVol;
        public double Vol
        {
            get { return fVol; }
            set { SetPropertyValue<double>("Vol", ref fVol, value); }
        }
        double fVolum;
        public double Volum
        {
            get { return fVolum; }
            set { SetPropertyValue<double>("Volum", ref fVolum, value); }
        }
        double fQuin;
        public double Quin
        {
            get { return fQuin; }
            set { SetPropertyValue<double>("Quin", ref fQuin, value); }
        }
        string fMaterialName;
        [Size(255)]
        [Persistent(@"Material Name")]
        public string MaterialName
        {
            get { return fMaterialName; }
            set { SetPropertyValue<string>("MaterialName", ref fMaterialName, value); }
        }
        string fBaseProduct;
        [Size(255)]
        [Persistent(@"Base Product")]
        public string BaseProduct
        {
            get { return fBaseProduct; }
            set { SetPropertyValue<string>("BaseProduct", ref fBaseProduct, value); }
        }
        string fBaseBaseProduct;
        [Size(255)]
        [Persistent(@"Base Base Product")]
        public string BaseBaseProduct
        {
            get { return fBaseBaseProduct; }
            set { SetPropertyValue<string>("BaseBaseProduct", ref fBaseBaseProduct, value); }
        }
        string fBrand;
        [Size(255)]
        public string Brand
        {
            get { return fBrand; }
            set { SetPropertyValue<string>("Brand", ref fBrand, value); }
        }
        string fName3Ar;
        [Size(255)]
        [Persistent(@"Name 3 Ar")]
        public string Name3Ar
        {
            get { return fName3Ar; }
            set { SetPropertyValue<string>("Name3Ar", ref fName3Ar, value); }
        }
        string fName1Ar;
        [Size(255)]
        [Persistent(@"Name 1 Ar")]
        public string Name1Ar
        {
            get { return fName1Ar; }
            set { SetPropertyValue<string>("Name1Ar", ref fName1Ar, value); }
        }
        string fYearC;
        [Size(255)]
        [Persistent(@"Year C")]
        public string YearC
        {
            get { return fYearC; }
            set { SetPropertyValue<string>("YearC", ref fYearC, value); }
        }
        string fCustomerType2;
        [Size(255)]
        [Persistent(@"Customer Type 2")]
        public string CustomerType2
        {
            get { return fCustomerType2; }
            set { SetPropertyValue<string>("CustomerType2", ref fCustomerType2, value); }
        }
        string fCustomerType;
        [Size(255)]
        [Persistent(@"Customer Type")]
        public string CustomerType
        {
            get { return fCustomerType; }
            set { SetPropertyValue<string>("CustomerType", ref fCustomerType, value); }
        }
        string fCustomerGroup;
        [Size(255)]
        [Persistent(@"Customer Group")]
        public string CustomerGroup
        {
            get { return fCustomerGroup; }
            set { SetPropertyValue<string>("CustomerGroup", ref fCustomerGroup, value); }
        }
        string fSubchannel;
        [Size(255)]
        public string Subchannel
        {
            get { return fSubchannel; }
            set { SetPropertyValue<string>("Subchannel", ref fSubchannel, value); }
        }
        string fL6Code;
        [Size(255)]
        [Persistent(@"L6 Code")]
        public string L6Code
        {
            get { return fL6Code; }
            set { SetPropertyValue<string>("L6Code", ref fL6Code, value); }
        }
        string fCustHierLevel6;
        [Size(255)]
        [Persistent(@"CustHier Level 6")]
        public string CustHierLevel6
        {
            get { return fCustHierLevel6; }
            set { SetPropertyValue<string>("CustHierLevel6", ref fCustHierLevel6, value); }
        }
        string fL5Code;
        [Size(255)]
        [Persistent(@"L5 Code")]
        public string L5Code
        {
            get { return fL5Code; }
            set { SetPropertyValue<string>("L5Code", ref fL5Code, value); }
        }
        string fCustHierLevel5;
        [Size(255)]
        [Persistent(@"CustHier Level 5")]
        public string CustHierLevel5
        {
            get { return fCustHierLevel5; }
            set { SetPropertyValue<string>("CustHierLevel5", ref fCustHierLevel5, value); }
        }
        string fL4Code;
        [Size(255)]
        [Persistent(@"L4 Code")]
        public string L4Code
        {
            get { return fL4Code; }
            set { SetPropertyValue<string>("L4Code", ref fL4Code, value); }
        }
        string fCustHierLevel4;
        [Size(255)]
        [Persistent(@"CustHier Level 4")]
        public string CustHierLevel4
        {
            get { return fCustHierLevel4; }
            set { SetPropertyValue<string>("CustHierLevel4", ref fCustHierLevel4, value); }
        }
        string fL3Code;
        [Size(255)]
        [Persistent(@"L3 Code")]
        public string L3Code
        {
            get { return fL3Code; }
            set { SetPropertyValue<string>("L3Code", ref fL3Code, value); }
        }
        string fCustHierLevel3;
        [Size(255)]
        [Persistent(@"CustHier Level 3")]
        public string CustHierLevel3
        {
            get { return fCustHierLevel3; }
            set { SetPropertyValue<string>("CustHierLevel3", ref fCustHierLevel3, value); }
        }
        string fName3En;
        [Size(255)]
        [Persistent(@"Name 3 En")]
        public string Name3En
        {
            get { return fName3En; }
            set { SetPropertyValue<string>("Name3En", ref fName3En, value); }
        }
        string fName1En;
        [Size(255)]
        [Persistent(@"Name 1 En")]
        public string Name1En
        {
            get { return fName1En; }
            set { SetPropertyValue<string>("Name1En", ref fName1En, value); }
        }
        string fBrandRoute;
        [Size(255)]
        [Persistent(@"Brand Route")]
        public string BrandRoute
        {
            get { return fBrandRoute; }
            set { SetPropertyValue<string>("BrandRoute", ref fBrandRoute, value); }
        }
        string fSupervisor;
        [Size(255)]
        public string Supervisor
        {
            get { return fSupervisor; }
            set { SetPropertyValue<string>("Supervisor", ref fSupervisor, value); }
        }
        string fASM;
        [Size(255)]
        public string ASM
        {
            get { return fASM; }
            set { SetPropertyValue<string>("ASM", ref fASM, value); }
        }
        string fRSM;
        [Size(255)]
        public string RSM
        {
            get { return fRSM; }
            set { SetPropertyValue<string>("RSM", ref fRSM, value); }
        }
        string fSalesDistrict;
        [Size(255)]
        [Persistent(@"Sales District")]
        public string SalesDistrict
        {
            get { return fSalesDistrict; }
            set { SetPropertyValue<string>("SalesDistrict", ref fSalesDistrict, value); }
        }
        string fSalesDistrictName;
        [Size(255)]
        [Persistent(@"Sales District Name")]
        public string SalesDistrictName
        {
            get { return fSalesDistrictName; }
            set { SetPropertyValue<string>("SalesDistrictName", ref fSalesDistrictName, value); }
        }
        string fRegion;
        [Size(255)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>("Region", ref fRegion, value); }
        }
        string fRouteName;
        [Size(255)]
        [Persistent(@"Route Name")]
        public string RouteName
        {
            get { return fRouteName; }
            set { SetPropertyValue<string>("RouteName", ref fRouteName, value); }
        }
        string fPeriod;
        [Size(255)]
        public string Period
        {
            get { return fPeriod; }
            set { SetPropertyValue<string>("Period", ref fPeriod, value); }
        }
        string fDay_Month;
        [Size(255)]
        [Persistent(@"Day-Month")]
        public string Day_Month
        {
            get { return fDay_Month; }
            set { SetPropertyValue<string>("Day_Month", ref fDay_Month, value); }
        }
        string fYear;
        [Size(255)]
        public string Year
        {
            get { return fYear; }
            set { SetPropertyValue<string>("Year", ref fYear, value); }
        }
        string fDay;
        [Size(255)]
        public string Day
        {
            get { return fDay; }
            set { SetPropertyValue<string>("Day", ref fDay, value); }
        }
        string fWeek;
        [Size(255)]
        public string Week
        {
            get { return fWeek; }
            set { SetPropertyValue<string>("Week", ref fWeek, value); }
        }
        int fSalesLD;
        [Persistent(@"Sales LD")]
        public int SalesLD
        {
            get { return fSalesLD; }
            set { SetPropertyValue<int>("SalesLD", ref fSalesLD, value); }
        }
        string fMonth;
        [Size(255)]
        public string Month
        {
            get { return fMonth; }
            set { SetPropertyValue<string>("Month", ref fMonth, value); }
        }
        string fUpdated;
        [Size(255)]
        public string Updated
        {
            get { return fUpdated; }
            set { SetPropertyValue<string>("Updated", ref fUpdated, value); }
        }
        double fAnnexrate;
        [Persistent(@"Annex rate")]
        public double Annexrate
        {
            get { return fAnnexrate; }
            set { SetPropertyValue<double>("Annexrate", ref fAnnexrate, value); }
        }
        string fAnnex;
        [Size(5)]
        public string Annex
        {
            get { return fAnnex; }
            set { SetPropertyValue<string>("Annex", ref fAnnex, value); }
        }
        int fNewQuanteite;
        [Persistent(@"New Quanteite")]
        public int NewQuanteite
        {
            get { return fNewQuanteite; }
            set { SetPropertyValue<int>("NewQuanteite", ref fNewQuanteite, value); }
        }
        string fyeard;
        [Size(50)]
        public string yeard
        {
            get { return fyeard; }
            set { SetPropertyValue<string>("yeard", ref fyeard, value); }
        }
        string fRoute_Sold;
        [Size(50)]
        [Persistent(@"Route & Sold")]
        public string Route_Sold
        {
            get { return fRoute_Sold; }
            set { SetPropertyValue<string>("Route_Sold", ref fRoute_Sold, value); }
        }
        double fConditionvalue;
        [Persistent(@"Condition value")]
        public double Conditionvalue
        {
            get { return fConditionvalue; }
            set { SetPropertyValue<double>("Conditionvalue", ref fConditionvalue, value); }
        }
        double fConditionbasevalue;
        [Persistent(@"Condition base value")]
        public double Conditionbasevalue
        {
            get { return fConditionbasevalue; }
            set { SetPropertyValue<double>("Conditionbasevalue", ref fConditionbasevalue, value); }
        }
        double fActualInvoicedQuan;
        [Persistent(@"Actual Invoiced Quan")]
        public double ActualInvoicedQuan
        {
            get { return fActualInvoicedQuan; }
            set { SetPropertyValue<double>("ActualInvoicedQuan", ref fActualInvoicedQuan, value); }
        }
        string fG_LAccountNumber;
        [Size(255)]
        [Persistent(@"G/L Account Number")]
        public string G_LAccountNumber
        {
            get { return fG_LAccountNumber; }
            set { SetPropertyValue<string>("G_LAccountNumber", ref fG_LAccountNumber, value); }
        }
        string fConditiontype;
        [Size(255)]
        [Persistent(@"Condition type")]
        public string Conditiontype
        {
            get { return fConditiontype; }
            set { SetPropertyValue<string>("Conditiontype", ref fConditiontype, value); }
        }
        string fPlant;
        [Size(255)]
        public string Plant
        {
            get { return fPlant; }
            set { SetPropertyValue<string>("Plant", ref fPlant, value); }
        }
        string fBaseUnitofMeasure;
        [Size(255)]
        [Persistent(@"Base Unit of Measure")]
        public string BaseUnitofMeasure
        {
            get { return fBaseUnitofMeasure; }
            set { SetPropertyValue<string>("BaseUnitofMeasure", ref fBaseUnitofMeasure, value); }
        }
        string fSalesunit;
        [Size(255)]
        [Persistent(@"Sales unit")]
        public string Salesunit
        {
            get { return fSalesunit; }
            set { SetPropertyValue<string>("Salesunit", ref fSalesunit, value); }
        }
        string fBillingitem;
        [Size(255)]
        [Persistent(@"Billing item")]
        public string Billingitem
        {
            get { return fBillingitem; }
            set { SetPropertyValue<string>("Billingitem", ref fBillingitem, value); }
        }
        string fReferenceDocumentN;
        [Size(255)]
        [Persistent(@"Reference Document N")]
        public string ReferenceDocumentN
        {
            get { return fReferenceDocumentN; }
            set { SetPropertyValue<string>("ReferenceDocumentN", ref fReferenceDocumentN, value); }
        }
        string fPayer;
        [Size(255)]
        public string Payer
        {
            get { return fPayer; }
            set { SetPropertyValue<string>("Payer", ref fPayer, value); }
        }
        string fCompanyCode;
        [Size(255)]
        [Persistent(@"Company Code")]
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>("CompanyCode", ref fCompanyCode, value); }
        }
        string fSalesOrganization;
        [Size(255)]
        [Persistent(@"Sales Organization")]
        public string SalesOrganization
        {
            get { return fSalesOrganization; }
            set { SetPropertyValue<string>("SalesOrganization", ref fSalesOrganization, value); }
        }
        string fBillingType;
        [Size(255)]
        [Persistent(@"Billing Type")]
        public string BillingType
        {
            get { return fBillingType; }
            set { SetPropertyValue<string>("BillingType", ref fBillingType, value); }
        }
        int fMaterialNumber;
        [Persistent(@"Material Number")]
        public int MaterialNumber
        {
            get { return fMaterialNumber; }
            set { SetPropertyValue<int>("MaterialNumber", ref fMaterialNumber, value); }
        }
        DateTime fBillingdateforbil;
        [Persistent(@"Billing date for bil")]
        public DateTime Billingdateforbil
        {
            get { return fBillingdateforbil; }
            set { SetPropertyValue<DateTime>("Billingdateforbil", ref fBillingdateforbil, value); }
        }
        string fRoute;
        [Size(50)]
        public string Route
        {
            get { return fRoute; }
            set { SetPropertyValue<string>("Route", ref fRoute, value); }
        }
        string fSold_toparty;
        [Size(255)]
        [Persistent(@"Sold-to party")]
        public string Sold_toparty
        {
            get { return fSold_toparty; }
            set { SetPropertyValue<string>("Sold_toparty", ref fSold_toparty, value); }
        }
        string fDistributionChannel;
        [Size(255)]
        [Persistent(@"Distribution Channel")]
        public string DistributionChannel
        {
            get { return fDistributionChannel; }
            set { SetPropertyValue<string>("DistributionChannel", ref fDistributionChannel, value); }
        }
        double fTPP;
        public double TPP
        {
            get { return fTPP; }
            set { SetPropertyValue<double>("TPP", ref fTPP, value); }
        }
        double fSales;
        public double Sales
        {
            get { return fSales; }
            set { SetPropertyValue<double>("Sales", ref fSales, value); }
        }
        string fBase_New;
        [Size(255)]
        [Persistent(@"Base-New")]
        public string Base_New
        {
            get { return fBase_New; }
            set { SetPropertyValue<string>("Base_New", ref fBase_New, value); }
        }
        string fLevelCCSD;
        [Size(255)]
        [Persistent(@"Level CCSD")]
        public string LevelCCSD
        {
            get { return fLevelCCSD; }
            set { SetPropertyValue<string>("LevelCCSD", ref fLevelCCSD, value); }
        }
        string fFRZbrand;
        [Size(255)]
        [Persistent(@"FRZ brand")]
        public string FRZbrand
        {
            get { return fFRZbrand; }
            set { SetPropertyValue<string>("FRZbrand", ref fFRZbrand, value); }
        }
        string fBrandRang;
        [Size(255)]
        [Persistent(@"Brand Rang")]
        public string BrandRang
        {
            get { return fBrandRang; }
            set { SetPropertyValue<string>("BrandRang", ref fBrandRang, value); }
        }
        string fP_SDN_Type;
        [Size(12)]
        [Persistent(@"#SDN-Type")]
        public string P_SDN_Type
        {
            get { return fP_SDN_Type; }
            set { SetPropertyValue<string>("P_SDN_Type", ref fP_SDN_Type, value); }
        }
        string fSalesDistrict2;
        [Size(255)]
        [Persistent(@"Sales District 2")]
        public string SalesDistrict2
        {
            get { return fSalesDistrict2; }
            set { SetPropertyValue<string>("SalesDistrict2", ref fSalesDistrict2, value); }
        }
        long fAutoKey;
        public long AutoKey
        {
            get { return fAutoKey; }
            set { SetPropertyValue<long>("AutoKey", ref fAutoKey, value); }
        }
        string fBaseGroup;
        [Size(255)]
        [Persistent(@"Base Group")]
        public string BaseGroup
        {
            get { return fBaseGroup; }
            set { SetPropertyValue<string>("BaseGroup", ref fBaseGroup, value); }
        }
    }

}
