//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class sp_DistributionWithZeroV1Result
    {
        public string Sold_toparty { get; set; }
        public string Active { get; set; }
        public string Name3Ar { get; set; }
        public string CustomerType2 { get; set; }
        public string CustomerType { get; set; }
        public string CustomerGroup { get; set; }
        public string Subchannel { get; set; }
        public string Name3En { get; set; }
        public string BrandRoute { get; set; }
        public string Supervisor { get; set; }
        public string ASM { get; set; }
        public string SalesDistrict { get; set; }
        public string SalesDistrictName { get; set; }
        public string Region { get; set; }
        public string RouteName { get; set; }
        public string DistributionChannel { get; set; }
        public string Route_Sold { get; set; }
        public DateTime LastINV { get; set; }
        public double Value14 { get; set; }
        public double Cases14 { get; set; }
    }

}
