//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class sp_DistributionV2Result
    {
        public string BaseBaseProduct { get; set; }
        public string SalesDistrict { get; set; }
        public int APOS14 { get; set; }
        public int APOS13 { get; set; }
        public int TAPOS14 { get; set; }
        public int TAPOS13 { get; set; }
    }

}
