//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class sp_SalesPerSKUV2Result
    {
        public string DistributionChannel { get; set; }
        public int MaterialNumber { get; set; }
        public string Plant { get; set; }
        public string Route_Sold { get; set; }
        public string yeard { get; set; }
        public string Month { get; set; }
        public string RouteName { get; set; }
        public string Region { get; set; }
        public string SalesDistrictName { get; set; }
        public string SalesDistrict { get; set; }
        public string SalesDistrict2 { get; set; }
        public string ASM { get; set; }
        public string Supervisor { get; set; }
        public string BrandRoute { get; set; }
        public string Subchannel { get; set; }
        public string CustomerGroup { get; set; }
        public string CustomerType { get; set; }
        public string CustomerType2 { get; set; }
        public string Brand { get; set; }
        public string BaseBaseProduct { get; set; }
        public string MaterialName { get; set; }
        public string PriceIncreas { get; set; }
        public string PricePointrang { get; set; }
        public string MaterialType { get; set; }
        public double PricePoint { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public string Group3 { get; set; }
        public string Type { get; set; }
        public double Cases13 { get; set; }
        public double Cases14 { get; set; }
        public double Value14 { get; set; }
        public double Value13 { get; set; }
        public double Cases { get; set; }
        public double Volume13 { get; set; }
        public double Volume14 { get; set; }
        public string BrandRang { get; set; }
        public string LevelCCSD { get; set; }
        public string P_SDN_Type { get; set; }
        public string CustomerBrand { get; set; }
        public double SalesEach13 { get; set; }
        public double SalesEach14 { get; set; }
    }

}
