//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class sp_Sales_KAResult
    {
        public string BillingDocument { get; set; }
        public double Value14 { get; set; }
        public double Value13 { get; set; }
        public double Cases14 { get; set; }
        public double Cases13 { get; set; }
        public string Type { get; set; }
        public string MaterialType { get; set; }
        public string SDNCode { get; set; }
        public string SDN_Custtype { get; set; }
        public string PricePointrang { get; set; }
        public string PriceIncreas { get; set; }
        public string MaterialName { get; set; }
        public string BaseBaseProduct { get; set; }
        public string Brand { get; set; }
        public string Name3Ar { get; set; }
        public string CustomerType2 { get; set; }
        public string CustomerType { get; set; }
        public string CustomerGroup { get; set; }
        public string Subchannel { get; set; }
        public string BrandRoute { get; set; }
        public string Supervisor { get; set; }
        public string ASM { get; set; }
        public string SalesDistrict { get; set; }
        public string SalesDistrictName { get; set; }
        public string SalesDistrict2 { get; set; }
        public string Region { get; set; }
        public string RouteName { get; set; }
        public string Day_Month { get; set; }
        public string yeard { get; set; }
        public string Route_Sold { get; set; }
        public int MaterialNumber { get; set; }
        public DateTime Billingdateforbil { get; set; }
        public string Sold_toparty { get; set; }
        public string DistributionChannel { get; set; }
        public string P_SDN_Type { get; set; }
        public string Base_New { get; set; }
        public string LevelCCSD { get; set; }
        public string FRZbrand { get; set; }
        public string Month { get; set; }
        public int INV13 { get; set; }
        public int INV14 { get; set; }
    }

}
