#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NICSQLTools.Data.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IC_DB")]
	public partial class dsLinqDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAppUser(AppUser instance);
    partial void UpdateAppUser(AppUser instance);
    partial void DeleteAppUser(AppUser instance);
    partial void InsertSalesDistrict3(SalesDistrict3 instance);
    partial void UpdateSalesDistrict3(SalesDistrict3 instance);
    partial void DeleteSalesDistrict3(SalesDistrict3 instance);
    partial void InsertSalesDistrict2(SalesDistrict2 instance);
    partial void UpdateSalesDistrict2(SalesDistrict2 instance);
    partial void DeleteSalesDistrict2(SalesDistrict2 instance);
    partial void InsertSalesDistrict1(SalesDistrict1 instance);
    partial void UpdateSalesDistrict1(SalesDistrict1 instance);
    partial void DeleteSalesDistrict1(SalesDistrict1 instance);
    partial void InsertvAppDashboardSchema_LUE(vAppDashboardSchema_LUE instance);
    partial void UpdatevAppDashboardSchema_LUE(vAppDashboardSchema_LUE instance);
    partial void DeletevAppDashboardSchema_LUE(vAppDashboardSchema_LUE instance);
    partial void InsertvAppDatasourceParam_LUE(vAppDatasourceParam_LUE instance);
    partial void UpdatevAppDatasourceParam_LUE(vAppDatasourceParam_LUE instance);
    partial void DeletevAppDatasourceParam_LUE(vAppDatasourceParam_LUE instance);
    partial void InsertvAppDatasourceLayout_LUE(vAppDatasourceLayout_LUE instance);
    partial void UpdatevAppDatasourceLayout_LUE(vAppDatasourceLayout_LUE instance);
    partial void DeletevAppDatasourceLayout_LUE(vAppDatasourceLayout_LUE instance);
    partial void InsertAppDatasourceType_LUE(AppDatasourceType_LUE instance);
    partial void UpdateAppDatasourceType_LUE(AppDatasourceType_LUE instance);
    partial void DeleteAppDatasourceType_LUE(AppDatasourceType_LUE instance);
    partial void InsertvAppDSCategory(vAppDSCategory instance);
    partial void UpdatevAppDSCategory(vAppDSCategory instance);
    partial void DeletevAppDSCategory(vAppDSCategory instance);
    partial void InsertPRD_BaseProduct(PRD_BaseProduct instance);
    partial void UpdatePRD_BaseProduct(PRD_BaseProduct instance);
    partial void DeletePRD_BaseProduct(PRD_BaseProduct instance);
    #endregion
		
		public dsLinqDataDataContext() : 
				base(global::NICSQLTools.Properties.Settings.Default.IC_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_0_0_Final_Data_All> _0_0_Final_Data_Alls
		{
			get
			{
				return this.GetTable<_0_0_Final_Data_All>();
			}
		}
		
		public System.Data.Linq.Table<AppUser> AppUsers
		{
			get
			{
				return this.GetTable<AppUser>();
			}
		}
		
		public System.Data.Linq.Table<SalesDistrict3> SalesDistrict3s
		{
			get
			{
				return this.GetTable<SalesDistrict3>();
			}
		}
		
		public System.Data.Linq.Table<SalesDistrict2> SalesDistrict2s
		{
			get
			{
				return this.GetTable<SalesDistrict2>();
			}
		}
		
		public System.Data.Linq.Table<SalesDistrict1> SalesDistrict1s
		{
			get
			{
				return this.GetTable<SalesDistrict1>();
			}
		}
		
		public System.Data.Linq.Table<vAppDashboardSchema_LUE> vAppDashboardSchema_LUEs
		{
			get
			{
				return this.GetTable<vAppDashboardSchema_LUE>();
			}
		}
		
		public System.Data.Linq.Table<vAppDatasourceParam_LUE> vAppDatasourceParam_LUEs
		{
			get
			{
				return this.GetTable<vAppDatasourceParam_LUE>();
			}
		}
		
		public System.Data.Linq.Table<vAppDatasourceLayout_LUE> vAppDatasourceLayout_LUEs
		{
			get
			{
				return this.GetTable<vAppDatasourceLayout_LUE>();
			}
		}
		
		public System.Data.Linq.Table<AppDatasourceType_LUE> AppDatasourceType_LUEs
		{
			get
			{
				return this.GetTable<AppDatasourceType_LUE>();
			}
		}
		
		public System.Data.Linq.Table<vAppDSCategory> vAppDSCategories
		{
			get
			{
				return this.GetTable<vAppDSCategory>();
			}
		}
		
		public System.Data.Linq.Table<PRD_BaseProduct> PRD_BaseProducts
		{
			get
			{
				return this.GetTable<PRD_BaseProduct>();
			}
		}
		
		public System.Data.Linq.Table<vAppDatasource_LUE> vAppDatasource_LUEs
		{
			get
			{
				return this.GetTable<vAppDatasource_LUE>();
			}
		}
		
		public System.Data.Linq.Table<vAppProductDetail> vAppProductDetails
		{
			get
			{
				return this.GetTable<vAppProductDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[0-0 Final Data All]")]
	public partial class _0_0_Final_Data_All
	{
		
		private string _Billing_Document;
		
		private System.Nullable<double> _Sales_Eh;
		
		private System.Nullable<double> _Volume_14;
		
		private System.Nullable<double> _Volume_13;
		
		private System.Nullable<double> _Value_14;
		
		private System.Nullable<double> _Value_13;
		
		private System.Nullable<double> _Value_12;
		
		private System.Nullable<double> _Value_11;
		
		private System.Nullable<double> _Cases_14;
		
		private System.Nullable<double> _Cases_13;
		
		private System.Nullable<double> _Cases_12;
		
		private System.Nullable<double> _Cases_11;
		
		private System.Nullable<double> _Volume;
		
		private System.Nullable<double> _New_Cases;
		
		private string _Type;
		
		private System.Nullable<double> _Cases;
		
		private System.Nullable<double> _Value;
		
		private System.Nullable<double> _Price_Point;
		
		private string _Material_Type;
		
		private System.Nullable<double> _Pallet;
		
		private System.Nullable<double> _Consumer_price__Piece;
		
		private string _Consumer_price__Carton;
		
		private string _Route_Number__system;
		
		private string _Group_3;
		
		private string _Group_2;
		
		private string _Group_1;
		
		private string _SDN_Code;
		
		private string _SDN__Custtype;
		
		private string _Address;
		
		private string _Customer_Type_STI;
		
		private System.Nullable<double> _Week_NCE;
		
		private System.Nullable<double> _Trade_Price_Piece;
		
		private System.Nullable<double> _Trade_Price_Carton;
		
		private string _Price_Point_rang;
		
		private string _Price_Increas;
		
		private System.Nullable<double> _New_Qu;
		
		private System.Nullable<double> _Volum_Pice;
		
		private System.Nullable<double> _Vol;
		
		private System.Nullable<double> _Volum;
		
		private System.Nullable<double> _Quin;
		
		private string _Material_Name;
		
		private string _Base_Product;
		
		private string _Base_Base_Product;
		
		private string _Brand;
		
		private string _Name_3_Ar;
		
		private string _Name_1_Ar;
		
		private string _Year_C;
		
		private string _Customer_Type_2;
		
		private string _Customer_Type;
		
		private string _Customer_Group;
		
		private string _Subchannel;
		
		private string _L6_Code;
		
		private string _CustHier_Level_6;
		
		private string _L5_Code;
		
		private string _CustHier_Level_5;
		
		private string _L4_Code;
		
		private string _CustHier_Level_4;
		
		private string _L3_Code;
		
		private string _CustHier_Level_3;
		
		private string _Name_3_En;
		
		private string _Name_1_En;
		
		private string _Brand_Route;
		
		private string _Supervisor;
		
		private string _ASM;
		
		private string _RSM;
		
		private string _Sales_District;
		
		private string _Sales_District_Name;
		
		private string _Region;
		
		private string _Route_Name;
		
		private string _Period;
		
		private string _Day_Month;
		
		private string _Year;
		
		private string _Day;
		
		private string _Week;
		
		private System.Nullable<int> _Sales_LD;
		
		private string _Month;
		
		private string _Updated;
		
		private System.Nullable<double> _Annex_rate;
		
		private string _Annex;
		
		private System.Nullable<double> _New_Quanteite;
		
		private string _yeard;
		
		private string _Route___Sold;
		
		private System.Nullable<double> _Condition_value;
		
		private System.Nullable<double> _Condition_base_value;
		
		private System.Nullable<double> _Actual_Invoiced_Quan;
		
		private string _G_L_Account_Number;
		
		private string _Condition_type;
		
		private string _Plant;
		
		private string _Base_Unit_of_Measure;
		
		private string _Sales_unit;
		
		private string _Billing_item;
		
		private string _Reference_Document_N;
		
		private string _Payer;
		
		private string _Company_Code;
		
		private string _Sales_Organization;
		
		private string _Billing_Type;
		
		private System.Nullable<int> _Material_Number;
		
		private System.Nullable<System.DateTime> _Billing_date_for_bil;
		
		private string _Route;
		
		private string _Sold_to_party;
		
		private string _Distribution_Channel;
		
		private System.Nullable<double> _TPP;
		
		private System.Nullable<double> _Sales;
		
		private string _Base_New;
		
		private string _Level_CCSD;
		
		private string _FRZ_brand;
		
		private string _Brand_Rang;
		
		private string @__SDN_Type;
		
		private string _Sales_District_2;
		
		private long _AutoKey;
		
		private string _Base_Group;
		
		private string _WOR_Period;
		
		private short _SalesDistrict1Id;
		
		private short _SalesDistrict2Id;
		
		private short _SalesDistrict3Id;
		
		private string _PriceCategory;
		
		private string _NCE_Project;
		
		public _0_0_Final_Data_All()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing Document]", Storage="_Billing_Document", DbType="NVarChar(255)")]
		public string Billing_Document
		{
			get
			{
				return this._Billing_Document;
			}
			set
			{
				if ((this._Billing_Document != value))
				{
					this._Billing_Document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales Eh]", Storage="_Sales_Eh", DbType="Float")]
		public System.Nullable<double> Sales_Eh
		{
			get
			{
				return this._Sales_Eh;
			}
			set
			{
				if ((this._Sales_Eh != value))
				{
					this._Sales_Eh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Volume 14]", Storage="_Volume_14", DbType="Float")]
		public System.Nullable<double> Volume_14
		{
			get
			{
				return this._Volume_14;
			}
			set
			{
				if ((this._Volume_14 != value))
				{
					this._Volume_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Volume 13]", Storage="_Volume_13", DbType="Float")]
		public System.Nullable<double> Volume_13
		{
			get
			{
				return this._Volume_13;
			}
			set
			{
				if ((this._Volume_13 != value))
				{
					this._Volume_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 14]", Storage="_Value_14", DbType="Float")]
		public System.Nullable<double> Value_14
		{
			get
			{
				return this._Value_14;
			}
			set
			{
				if ((this._Value_14 != value))
				{
					this._Value_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 13]", Storage="_Value_13", DbType="Float")]
		public System.Nullable<double> Value_13
		{
			get
			{
				return this._Value_13;
			}
			set
			{
				if ((this._Value_13 != value))
				{
					this._Value_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 12]", Storage="_Value_12", DbType="Float")]
		public System.Nullable<double> Value_12
		{
			get
			{
				return this._Value_12;
			}
			set
			{
				if ((this._Value_12 != value))
				{
					this._Value_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 11]", Storage="_Value_11", DbType="Float")]
		public System.Nullable<double> Value_11
		{
			get
			{
				return this._Value_11;
			}
			set
			{
				if ((this._Value_11 != value))
				{
					this._Value_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 14]", Storage="_Cases_14", DbType="Float")]
		public System.Nullable<double> Cases_14
		{
			get
			{
				return this._Cases_14;
			}
			set
			{
				if ((this._Cases_14 != value))
				{
					this._Cases_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 13]", Storage="_Cases_13", DbType="Float")]
		public System.Nullable<double> Cases_13
		{
			get
			{
				return this._Cases_13;
			}
			set
			{
				if ((this._Cases_13 != value))
				{
					this._Cases_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 12]", Storage="_Cases_12", DbType="Float")]
		public System.Nullable<double> Cases_12
		{
			get
			{
				return this._Cases_12;
			}
			set
			{
				if ((this._Cases_12 != value))
				{
					this._Cases_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 11]", Storage="_Cases_11", DbType="Float")]
		public System.Nullable<double> Cases_11
		{
			get
			{
				return this._Cases_11;
			}
			set
			{
				if ((this._Cases_11 != value))
				{
					this._Cases_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float")]
		public System.Nullable<double> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this._Volume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Cases]", Storage="_New_Cases", DbType="Float")]
		public System.Nullable<double> New_Cases
		{
			get
			{
				return this._New_Cases;
			}
			set
			{
				if ((this._New_Cases != value))
				{
					this._New_Cases = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cases", DbType="Float")]
		public System.Nullable<double> Cases
		{
			get
			{
				return this._Cases;
			}
			set
			{
				if ((this._Cases != value))
				{
					this._Cases = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Price Point]", Storage="_Price_Point", DbType="Float")]
		public System.Nullable<double> Price_Point
		{
			get
			{
				return this._Price_Point;
			}
			set
			{
				if ((this._Price_Point != value))
				{
					this._Price_Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Type]", Storage="_Material_Type", DbType="NVarChar(255)")]
		public string Material_Type
		{
			get
			{
				return this._Material_Type;
			}
			set
			{
				if ((this._Material_Type != value))
				{
					this._Material_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pallet", DbType="Float")]
		public System.Nullable<double> Pallet
		{
			get
			{
				return this._Pallet;
			}
			set
			{
				if ((this._Pallet != value))
				{
					this._Pallet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Consumer price /Piece]", Storage="_Consumer_price__Piece", DbType="Float")]
		public System.Nullable<double> Consumer_price__Piece
		{
			get
			{
				return this._Consumer_price__Piece;
			}
			set
			{
				if ((this._Consumer_price__Piece != value))
				{
					this._Consumer_price__Piece = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Consumer price /Carton]", Storage="_Consumer_price__Carton", DbType="NVarChar(255)")]
		public string Consumer_price__Carton
		{
			get
			{
				return this._Consumer_price__Carton;
			}
			set
			{
				if ((this._Consumer_price__Carton != value))
				{
					this._Consumer_price__Carton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Route Number  system]", Storage="_Route_Number__system", DbType="NVarChar(255)")]
		public string Route_Number__system
		{
			get
			{
				return this._Route_Number__system;
			}
			set
			{
				if ((this._Route_Number__system != value))
				{
					this._Route_Number__system = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group 3]", Storage="_Group_3", DbType="NVarChar(255)")]
		public string Group_3
		{
			get
			{
				return this._Group_3;
			}
			set
			{
				if ((this._Group_3 != value))
				{
					this._Group_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group 2]", Storage="_Group_2", DbType="NVarChar(255)")]
		public string Group_2
		{
			get
			{
				return this._Group_2;
			}
			set
			{
				if ((this._Group_2 != value))
				{
					this._Group_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group 1]", Storage="_Group_1", DbType="NVarChar(255)")]
		public string Group_1
		{
			get
			{
				return this._Group_1;
			}
			set
			{
				if ((this._Group_1 != value))
				{
					this._Group_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SDN Code]", Storage="_SDN_Code", DbType="NVarChar(255)")]
		public string SDN_Code
		{
			get
			{
				return this._SDN_Code;
			}
			set
			{
				if ((this._SDN_Code != value))
				{
					this._SDN_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SDN &Custtype]", Storage="_SDN__Custtype", DbType="NVarChar(265)")]
		public string SDN__Custtype
		{
			get
			{
				return this._SDN__Custtype;
			}
			set
			{
				if ((this._SDN__Custtype != value))
				{
					this._SDN__Custtype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Type_STI]", Storage="_Customer_Type_STI", DbType="NVarChar(255)")]
		public string Customer_Type_STI
		{
			get
			{
				return this._Customer_Type_STI;
			}
			set
			{
				if ((this._Customer_Type_STI != value))
				{
					this._Customer_Type_STI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Week NCE]", Storage="_Week_NCE", DbType="Float")]
		public System.Nullable<double> Week_NCE
		{
			get
			{
				return this._Week_NCE;
			}
			set
			{
				if ((this._Week_NCE != value))
				{
					this._Week_NCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Trade Price/Piece]", Storage="_Trade_Price_Piece", DbType="Float")]
		public System.Nullable<double> Trade_Price_Piece
		{
			get
			{
				return this._Trade_Price_Piece;
			}
			set
			{
				if ((this._Trade_Price_Piece != value))
				{
					this._Trade_Price_Piece = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Trade Price/Carton]", Storage="_Trade_Price_Carton", DbType="Float")]
		public System.Nullable<double> Trade_Price_Carton
		{
			get
			{
				return this._Trade_Price_Carton;
			}
			set
			{
				if ((this._Trade_Price_Carton != value))
				{
					this._Trade_Price_Carton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Price Point rang]", Storage="_Price_Point_rang", DbType="NVarChar(255)")]
		public string Price_Point_rang
		{
			get
			{
				return this._Price_Point_rang;
			}
			set
			{
				if ((this._Price_Point_rang != value))
				{
					this._Price_Point_rang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Price Increas]", Storage="_Price_Increas", DbType="NVarChar(255)")]
		public string Price_Increas
		{
			get
			{
				return this._Price_Increas;
			}
			set
			{
				if ((this._Price_Increas != value))
				{
					this._Price_Increas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Qu]", Storage="_New_Qu", DbType="Float")]
		public System.Nullable<double> New_Qu
		{
			get
			{
				return this._New_Qu;
			}
			set
			{
				if ((this._New_Qu != value))
				{
					this._New_Qu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Volum Pice]", Storage="_Volum_Pice", DbType="Float")]
		public System.Nullable<double> Volum_Pice
		{
			get
			{
				return this._Volum_Pice;
			}
			set
			{
				if ((this._Volum_Pice != value))
				{
					this._Volum_Pice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol", DbType="Float")]
		public System.Nullable<double> Vol
		{
			get
			{
				return this._Vol;
			}
			set
			{
				if ((this._Vol != value))
				{
					this._Vol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volum", DbType="Float")]
		public System.Nullable<double> Volum
		{
			get
			{
				return this._Volum;
			}
			set
			{
				if ((this._Volum != value))
				{
					this._Volum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quin", DbType="Float")]
		public System.Nullable<double> Quin
		{
			get
			{
				return this._Quin;
			}
			set
			{
				if ((this._Quin != value))
				{
					this._Quin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Name]", Storage="_Material_Name", DbType="NVarChar(255)")]
		public string Material_Name
		{
			get
			{
				return this._Material_Name;
			}
			set
			{
				if ((this._Material_Name != value))
				{
					this._Material_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Product]", Storage="_Base_Product", DbType="NVarChar(255)")]
		public string Base_Product
		{
			get
			{
				return this._Base_Product;
			}
			set
			{
				if ((this._Base_Product != value))
				{
					this._Base_Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Base Product]", Storage="_Base_Base_Product", DbType="NVarChar(255)")]
		public string Base_Base_Product
		{
			get
			{
				return this._Base_Base_Product;
			}
			set
			{
				if ((this._Base_Base_Product != value))
				{
					this._Base_Base_Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="NVarChar(255)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 3 Ar]", Storage="_Name_3_Ar", DbType="NVarChar(255)")]
		public string Name_3_Ar
		{
			get
			{
				return this._Name_3_Ar;
			}
			set
			{
				if ((this._Name_3_Ar != value))
				{
					this._Name_3_Ar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 1 Ar]", Storage="_Name_1_Ar", DbType="NVarChar(255)")]
		public string Name_1_Ar
		{
			get
			{
				return this._Name_1_Ar;
			}
			set
			{
				if ((this._Name_1_Ar != value))
				{
					this._Name_1_Ar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Year C]", Storage="_Year_C", DbType="NVarChar(255)")]
		public string Year_C
		{
			get
			{
				return this._Year_C;
			}
			set
			{
				if ((this._Year_C != value))
				{
					this._Year_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Type 2]", Storage="_Customer_Type_2", DbType="NVarChar(255)")]
		public string Customer_Type_2
		{
			get
			{
				return this._Customer_Type_2;
			}
			set
			{
				if ((this._Customer_Type_2 != value))
				{
					this._Customer_Type_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Type]", Storage="_Customer_Type", DbType="NVarChar(255)")]
		public string Customer_Type
		{
			get
			{
				return this._Customer_Type;
			}
			set
			{
				if ((this._Customer_Type != value))
				{
					this._Customer_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Group]", Storage="_Customer_Group", DbType="NVarChar(255)")]
		public string Customer_Group
		{
			get
			{
				return this._Customer_Group;
			}
			set
			{
				if ((this._Customer_Group != value))
				{
					this._Customer_Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subchannel", DbType="NVarChar(255)")]
		public string Subchannel
		{
			get
			{
				return this._Subchannel;
			}
			set
			{
				if ((this._Subchannel != value))
				{
					this._Subchannel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[L6 Code]", Storage="_L6_Code", DbType="NVarChar(255)")]
		public string L6_Code
		{
			get
			{
				return this._L6_Code;
			}
			set
			{
				if ((this._L6_Code != value))
				{
					this._L6_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CustHier Level 6]", Storage="_CustHier_Level_6", DbType="NVarChar(255)")]
		public string CustHier_Level_6
		{
			get
			{
				return this._CustHier_Level_6;
			}
			set
			{
				if ((this._CustHier_Level_6 != value))
				{
					this._CustHier_Level_6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[L5 Code]", Storage="_L5_Code", DbType="NVarChar(255)")]
		public string L5_Code
		{
			get
			{
				return this._L5_Code;
			}
			set
			{
				if ((this._L5_Code != value))
				{
					this._L5_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CustHier Level 5]", Storage="_CustHier_Level_5", DbType="NVarChar(255)")]
		public string CustHier_Level_5
		{
			get
			{
				return this._CustHier_Level_5;
			}
			set
			{
				if ((this._CustHier_Level_5 != value))
				{
					this._CustHier_Level_5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[L4 Code]", Storage="_L4_Code", DbType="NVarChar(255)")]
		public string L4_Code
		{
			get
			{
				return this._L4_Code;
			}
			set
			{
				if ((this._L4_Code != value))
				{
					this._L4_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CustHier Level 4]", Storage="_CustHier_Level_4", DbType="NVarChar(255)")]
		public string CustHier_Level_4
		{
			get
			{
				return this._CustHier_Level_4;
			}
			set
			{
				if ((this._CustHier_Level_4 != value))
				{
					this._CustHier_Level_4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[L3 Code]", Storage="_L3_Code", DbType="NVarChar(255)")]
		public string L3_Code
		{
			get
			{
				return this._L3_Code;
			}
			set
			{
				if ((this._L3_Code != value))
				{
					this._L3_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CustHier Level 3]", Storage="_CustHier_Level_3", DbType="NVarChar(255)")]
		public string CustHier_Level_3
		{
			get
			{
				return this._CustHier_Level_3;
			}
			set
			{
				if ((this._CustHier_Level_3 != value))
				{
					this._CustHier_Level_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 3 En]", Storage="_Name_3_En", DbType="NVarChar(255)")]
		public string Name_3_En
		{
			get
			{
				return this._Name_3_En;
			}
			set
			{
				if ((this._Name_3_En != value))
				{
					this._Name_3_En = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 1 En]", Storage="_Name_1_En", DbType="NVarChar(255)")]
		public string Name_1_En
		{
			get
			{
				return this._Name_1_En;
			}
			set
			{
				if ((this._Name_1_En != value))
				{
					this._Name_1_En = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Brand Route]", Storage="_Brand_Route", DbType="NVarChar(255)")]
		public string Brand_Route
		{
			get
			{
				return this._Brand_Route;
			}
			set
			{
				if ((this._Brand_Route != value))
				{
					this._Brand_Route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="NVarChar(255)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this._Supervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASM", DbType="NVarChar(255)")]
		public string ASM
		{
			get
			{
				return this._ASM;
			}
			set
			{
				if ((this._ASM != value))
				{
					this._ASM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSM", DbType="NVarChar(255)")]
		public string RSM
		{
			get
			{
				return this._RSM;
			}
			set
			{
				if ((this._RSM != value))
				{
					this._RSM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District]", Storage="_Sales_District", DbType="NVarChar(50)")]
		public string Sales_District
		{
			get
			{
				return this._Sales_District;
			}
			set
			{
				if ((this._Sales_District != value))
				{
					this._Sales_District = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District Name]", Storage="_Sales_District_Name", DbType="NVarChar(50)")]
		public string Sales_District_Name
		{
			get
			{
				return this._Sales_District_Name;
			}
			set
			{
				if ((this._Sales_District_Name != value))
				{
					this._Sales_District_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(255)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Route Name]", Storage="_Route_Name", DbType="NVarChar(255)")]
		public string Route_Name
		{
			get
			{
				return this._Route_Name;
			}
			set
			{
				if ((this._Route_Name != value))
				{
					this._Route_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NVarChar(255)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this._Period = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Day-Month]", Storage="_Day_Month", DbType="NVarChar(255)")]
		public string Day_Month
		{
			get
			{
				return this._Day_Month;
			}
			set
			{
				if ((this._Day_Month != value))
				{
					this._Day_Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(255)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="NVarChar(255)")]
		public string Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Week", DbType="NVarChar(255)")]
		public string Week
		{
			get
			{
				return this._Week;
			}
			set
			{
				if ((this._Week != value))
				{
					this._Week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales LD]", Storage="_Sales_LD", DbType="Int")]
		public System.Nullable<int> Sales_LD
		{
			get
			{
				return this._Sales_LD;
			}
			set
			{
				if ((this._Sales_LD != value))
				{
					this._Sales_LD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(255)")]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="NVarChar(255)")]
		public string Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Annex rate]", Storage="_Annex_rate", DbType="Float")]
		public System.Nullable<double> Annex_rate
		{
			get
			{
				return this._Annex_rate;
			}
			set
			{
				if ((this._Annex_rate != value))
				{
					this._Annex_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annex", DbType="VarChar(5)")]
		public string Annex
		{
			get
			{
				return this._Annex;
			}
			set
			{
				if ((this._Annex != value))
				{
					this._Annex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Quanteite]", Storage="_New_Quanteite", DbType="Float")]
		public System.Nullable<double> New_Quanteite
		{
			get
			{
				return this._New_Quanteite;
			}
			set
			{
				if ((this._New_Quanteite != value))
				{
					this._New_Quanteite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeard", DbType="NVarChar(50)")]
		public string yeard
		{
			get
			{
				return this._yeard;
			}
			set
			{
				if ((this._yeard != value))
				{
					this._yeard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Route & Sold]", Storage="_Route___Sold", DbType="NVarChar(50)")]
		public string Route___Sold
		{
			get
			{
				return this._Route___Sold;
			}
			set
			{
				if ((this._Route___Sold != value))
				{
					this._Route___Sold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Condition value]", Storage="_Condition_value", DbType="Float")]
		public System.Nullable<double> Condition_value
		{
			get
			{
				return this._Condition_value;
			}
			set
			{
				if ((this._Condition_value != value))
				{
					this._Condition_value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Condition base value]", Storage="_Condition_base_value", DbType="Float")]
		public System.Nullable<double> Condition_base_value
		{
			get
			{
				return this._Condition_base_value;
			}
			set
			{
				if ((this._Condition_base_value != value))
				{
					this._Condition_base_value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Actual Invoiced Quan]", Storage="_Actual_Invoiced_Quan", DbType="Float")]
		public System.Nullable<double> Actual_Invoiced_Quan
		{
			get
			{
				return this._Actual_Invoiced_Quan;
			}
			set
			{
				if ((this._Actual_Invoiced_Quan != value))
				{
					this._Actual_Invoiced_Quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[G/L Account Number]", Storage="_G_L_Account_Number", DbType="NVarChar(255)")]
		public string G_L_Account_Number
		{
			get
			{
				return this._G_L_Account_Number;
			}
			set
			{
				if ((this._G_L_Account_Number != value))
				{
					this._G_L_Account_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Condition type]", Storage="_Condition_type", DbType="NVarChar(255)")]
		public string Condition_type
		{
			get
			{
				return this._Condition_type;
			}
			set
			{
				if ((this._Condition_type != value))
				{
					this._Condition_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plant", DbType="NVarChar(255)")]
		public string Plant
		{
			get
			{
				return this._Plant;
			}
			set
			{
				if ((this._Plant != value))
				{
					this._Plant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Unit of Measure]", Storage="_Base_Unit_of_Measure", DbType="NVarChar(255)")]
		public string Base_Unit_of_Measure
		{
			get
			{
				return this._Base_Unit_of_Measure;
			}
			set
			{
				if ((this._Base_Unit_of_Measure != value))
				{
					this._Base_Unit_of_Measure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales unit]", Storage="_Sales_unit", DbType="NVarChar(255)")]
		public string Sales_unit
		{
			get
			{
				return this._Sales_unit;
			}
			set
			{
				if ((this._Sales_unit != value))
				{
					this._Sales_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing item]", Storage="_Billing_item", DbType="NVarChar(255)")]
		public string Billing_item
		{
			get
			{
				return this._Billing_item;
			}
			set
			{
				if ((this._Billing_item != value))
				{
					this._Billing_item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Reference Document N]", Storage="_Reference_Document_N", DbType="NVarChar(255)")]
		public string Reference_Document_N
		{
			get
			{
				return this._Reference_Document_N;
			}
			set
			{
				if ((this._Reference_Document_N != value))
				{
					this._Reference_Document_N = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payer", DbType="NVarChar(255)")]
		public string Payer
		{
			get
			{
				return this._Payer;
			}
			set
			{
				if ((this._Payer != value))
				{
					this._Payer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Company Code]", Storage="_Company_Code", DbType="NVarChar(255)")]
		public string Company_Code
		{
			get
			{
				return this._Company_Code;
			}
			set
			{
				if ((this._Company_Code != value))
				{
					this._Company_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales Organization]", Storage="_Sales_Organization", DbType="NVarChar(255)")]
		public string Sales_Organization
		{
			get
			{
				return this._Sales_Organization;
			}
			set
			{
				if ((this._Sales_Organization != value))
				{
					this._Sales_Organization = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing Type]", Storage="_Billing_Type", DbType="NVarChar(255)")]
		public string Billing_Type
		{
			get
			{
				return this._Billing_Type;
			}
			set
			{
				if ((this._Billing_Type != value))
				{
					this._Billing_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Number]", Storage="_Material_Number", DbType="Int")]
		public System.Nullable<int> Material_Number
		{
			get
			{
				return this._Material_Number;
			}
			set
			{
				if ((this._Material_Number != value))
				{
					this._Material_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing date for bil]", Storage="_Billing_date_for_bil", DbType="DateTime")]
		public System.Nullable<System.DateTime> Billing_date_for_bil
		{
			get
			{
				return this._Billing_date_for_bil;
			}
			set
			{
				if ((this._Billing_date_for_bil != value))
				{
					this._Billing_date_for_bil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="NVarChar(50)")]
		public string Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this._Route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sold-to party]", Storage="_Sold_to_party", DbType="NVarChar(255)")]
		public string Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this._Sold_to_party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Distribution Channel]", Storage="_Distribution_Channel", DbType="NVarChar(255)")]
		public string Distribution_Channel
		{
			get
			{
				return this._Distribution_Channel;
			}
			set
			{
				if ((this._Distribution_Channel != value))
				{
					this._Distribution_Channel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPP", DbType="Float")]
		public System.Nullable<double> TPP
		{
			get
			{
				return this._TPP;
			}
			set
			{
				if ((this._TPP != value))
				{
					this._TPP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sales", DbType="Float")]
		public System.Nullable<double> Sales
		{
			get
			{
				return this._Sales;
			}
			set
			{
				if ((this._Sales != value))
				{
					this._Sales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base-New]", Storage="_Base_New", DbType="NVarChar(255)")]
		public string Base_New
		{
			get
			{
				return this._Base_New;
			}
			set
			{
				if ((this._Base_New != value))
				{
					this._Base_New = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level CCSD]", Storage="_Level_CCSD", DbType="NVarChar(255)")]
		public string Level_CCSD
		{
			get
			{
				return this._Level_CCSD;
			}
			set
			{
				if ((this._Level_CCSD != value))
				{
					this._Level_CCSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FRZ brand]", Storage="_FRZ_brand", DbType="NVarChar(255)")]
		public string FRZ_brand
		{
			get
			{
				return this._FRZ_brand;
			}
			set
			{
				if ((this._FRZ_brand != value))
				{
					this._FRZ_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Brand Rang]", Storage="_Brand_Rang", DbType="NVarChar(255)")]
		public string Brand_Rang
		{
			get
			{
				return this._Brand_Rang;
			}
			set
			{
				if ((this._Brand_Rang != value))
				{
					this._Brand_Rang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[#SDN-Type]", Storage="__SDN_Type", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string _SDN_Type
		{
			get
			{
				return this.@__SDN_Type;
			}
			set
			{
				if ((this.@__SDN_Type != value))
				{
					this.@__SDN_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District 2]", Storage="_Sales_District_2", DbType="NVarChar(50)")]
		public string Sales_District_2
		{
			get
			{
				return this._Sales_District_2;
			}
			set
			{
				if ((this._Sales_District_2 != value))
				{
					this._Sales_District_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", DbType="BigInt NOT NULL")]
		public long AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this._AutoKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Group]", Storage="_Base_Group", DbType="NVarChar(255)")]
		public string Base_Group
		{
			get
			{
				return this._Base_Group;
			}
			set
			{
				if ((this._Base_Group != value))
				{
					this._Base_Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WOR_Period", DbType="NVarChar(255)")]
		public string WOR_Period
		{
			get
			{
				return this._WOR_Period;
			}
			set
			{
				if ((this._WOR_Period != value))
				{
					this._WOR_Period = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict1Id", DbType="SmallInt NOT NULL")]
		public short SalesDistrict1Id
		{
			get
			{
				return this._SalesDistrict1Id;
			}
			set
			{
				if ((this._SalesDistrict1Id != value))
				{
					this._SalesDistrict1Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict2Id", DbType="SmallInt NOT NULL")]
		public short SalesDistrict2Id
		{
			get
			{
				return this._SalesDistrict2Id;
			}
			set
			{
				if ((this._SalesDistrict2Id != value))
				{
					this._SalesDistrict2Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict3Id", DbType="SmallInt NOT NULL")]
		public short SalesDistrict3Id
		{
			get
			{
				return this._SalesDistrict3Id;
			}
			set
			{
				if ((this._SalesDistrict3Id != value))
				{
					this._SalesDistrict3Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceCategory", DbType="NVarChar(50)")]
		public string PriceCategory
		{
			get
			{
				return this._PriceCategory;
			}
			set
			{
				if ((this._PriceCategory != value))
				{
					this._PriceCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCE_Project", DbType="NVarChar(255)")]
		public string NCE_Project
		{
			get
			{
				return this._NCE_Project;
			}
			set
			{
				if ((this._NCE_Project != value))
				{
					this._NCE_Project = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppUsers")]
	public partial class AppUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _RealName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    #endregion
		
		public AppUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesDistrict3")]
	public partial class SalesDistrict3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _SalesDistrict3Id;
		
		private string _Sales_District_2;
		
		private System.Nullable<short> _SalesDistrict2Id;
		
		private EntityRef<SalesDistrict2> _SalesDistrict2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalesDistrict3IdChanging(short value);
    partial void OnSalesDistrict3IdChanged();
    partial void OnSales_District_2Changing(string value);
    partial void OnSales_District_2Changed();
    partial void OnSalesDistrict2IdChanging(System.Nullable<short> value);
    partial void OnSalesDistrict2IdChanged();
    #endregion
		
		public SalesDistrict3()
		{
			this._SalesDistrict2 = default(EntityRef<SalesDistrict2>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict3Id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short SalesDistrict3Id
		{
			get
			{
				return this._SalesDistrict3Id;
			}
			set
			{
				if ((this._SalesDistrict3Id != value))
				{
					this.OnSalesDistrict3IdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict3Id = value;
					this.SendPropertyChanged("SalesDistrict3Id");
					this.OnSalesDistrict3IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District 2]", Storage="_Sales_District_2", DbType="NVarChar(50)")]
		public string Sales_District_2
		{
			get
			{
				return this._Sales_District_2;
			}
			set
			{
				if ((this._Sales_District_2 != value))
				{
					this.OnSales_District_2Changing(value);
					this.SendPropertyChanging();
					this._Sales_District_2 = value;
					this.SendPropertyChanged("Sales_District_2");
					this.OnSales_District_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict2Id", DbType="SmallInt")]
		public System.Nullable<short> SalesDistrict2Id
		{
			get
			{
				return this._SalesDistrict2Id;
			}
			set
			{
				if ((this._SalesDistrict2Id != value))
				{
					if (this._SalesDistrict2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSalesDistrict2IdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict2Id = value;
					this.SendPropertyChanged("SalesDistrict2Id");
					this.OnSalesDistrict2IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SalesDistrict2_SalesDistrict3", Storage="_SalesDistrict2", ThisKey="SalesDistrict2Id", OtherKey="SalesDistrict2Id", IsForeignKey=true)]
		public SalesDistrict2 SalesDistrict2
		{
			get
			{
				return this._SalesDistrict2.Entity;
			}
			set
			{
				SalesDistrict2 previousValue = this._SalesDistrict2.Entity;
				if (((previousValue != value) 
							|| (this._SalesDistrict2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SalesDistrict2.Entity = null;
						previousValue.SalesDistrict3s.Remove(this);
					}
					this._SalesDistrict2.Entity = value;
					if ((value != null))
					{
						value.SalesDistrict3s.Add(this);
						this._SalesDistrict2Id = value.SalesDistrict2Id;
					}
					else
					{
						this._SalesDistrict2Id = default(Nullable<short>);
					}
					this.SendPropertyChanged("SalesDistrict2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesDistrict2")]
	public partial class SalesDistrict2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _SalesDistrict2Id;
		
		private string _Sales_District;
		
		private System.Nullable<short> _SalesDistrict1Id;
		
		private EntitySet<SalesDistrict3> _SalesDistrict3s;
		
		private EntityRef<SalesDistrict1> _SalesDistrict1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalesDistrict2IdChanging(short value);
    partial void OnSalesDistrict2IdChanged();
    partial void OnSales_DistrictChanging(string value);
    partial void OnSales_DistrictChanged();
    partial void OnSalesDistrict1IdChanging(System.Nullable<short> value);
    partial void OnSalesDistrict1IdChanged();
    #endregion
		
		public SalesDistrict2()
		{
			this._SalesDistrict3s = new EntitySet<SalesDistrict3>(new Action<SalesDistrict3>(this.attach_SalesDistrict3s), new Action<SalesDistrict3>(this.detach_SalesDistrict3s));
			this._SalesDistrict1 = default(EntityRef<SalesDistrict1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict2Id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short SalesDistrict2Id
		{
			get
			{
				return this._SalesDistrict2Id;
			}
			set
			{
				if ((this._SalesDistrict2Id != value))
				{
					this.OnSalesDistrict2IdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict2Id = value;
					this.SendPropertyChanged("SalesDistrict2Id");
					this.OnSalesDistrict2IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District]", Storage="_Sales_District", DbType="NVarChar(50)")]
		public string Sales_District
		{
			get
			{
				return this._Sales_District;
			}
			set
			{
				if ((this._Sales_District != value))
				{
					this.OnSales_DistrictChanging(value);
					this.SendPropertyChanging();
					this._Sales_District = value;
					this.SendPropertyChanged("Sales_District");
					this.OnSales_DistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict1Id", DbType="SmallInt")]
		public System.Nullable<short> SalesDistrict1Id
		{
			get
			{
				return this._SalesDistrict1Id;
			}
			set
			{
				if ((this._SalesDistrict1Id != value))
				{
					if (this._SalesDistrict1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSalesDistrict1IdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict1Id = value;
					this.SendPropertyChanged("SalesDistrict1Id");
					this.OnSalesDistrict1IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SalesDistrict2_SalesDistrict3", Storage="_SalesDistrict3s", ThisKey="SalesDistrict2Id", OtherKey="SalesDistrict2Id")]
		public EntitySet<SalesDistrict3> SalesDistrict3s
		{
			get
			{
				return this._SalesDistrict3s;
			}
			set
			{
				this._SalesDistrict3s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SalesDistrict1_SalesDistrict2", Storage="_SalesDistrict1", ThisKey="SalesDistrict1Id", OtherKey="SalesDistrict1Id", IsForeignKey=true)]
		public SalesDistrict1 SalesDistrict1
		{
			get
			{
				return this._SalesDistrict1.Entity;
			}
			set
			{
				SalesDistrict1 previousValue = this._SalesDistrict1.Entity;
				if (((previousValue != value) 
							|| (this._SalesDistrict1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SalesDistrict1.Entity = null;
						previousValue.SalesDistrict2s.Remove(this);
					}
					this._SalesDistrict1.Entity = value;
					if ((value != null))
					{
						value.SalesDistrict2s.Add(this);
						this._SalesDistrict1Id = value.SalesDistrict1Id;
					}
					else
					{
						this._SalesDistrict1Id = default(Nullable<short>);
					}
					this.SendPropertyChanged("SalesDistrict1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SalesDistrict3s(SalesDistrict3 entity)
		{
			this.SendPropertyChanging();
			entity.SalesDistrict2 = this;
		}
		
		private void detach_SalesDistrict3s(SalesDistrict3 entity)
		{
			this.SendPropertyChanging();
			entity.SalesDistrict2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesDistrict1")]
	public partial class SalesDistrict1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _SalesDistrict1Id;
		
		private string _Sales_District_Name;
		
		private EntitySet<SalesDistrict2> _SalesDistrict2s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalesDistrict1IdChanging(short value);
    partial void OnSalesDistrict1IdChanged();
    partial void OnSales_District_NameChanging(string value);
    partial void OnSales_District_NameChanged();
    #endregion
		
		public SalesDistrict1()
		{
			this._SalesDistrict2s = new EntitySet<SalesDistrict2>(new Action<SalesDistrict2>(this.attach_SalesDistrict2s), new Action<SalesDistrict2>(this.detach_SalesDistrict2s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict1Id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short SalesDistrict1Id
		{
			get
			{
				return this._SalesDistrict1Id;
			}
			set
			{
				if ((this._SalesDistrict1Id != value))
				{
					this.OnSalesDistrict1IdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict1Id = value;
					this.SendPropertyChanged("SalesDistrict1Id");
					this.OnSalesDistrict1IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District Name]", Storage="_Sales_District_Name", DbType="NVarChar(50)")]
		public string Sales_District_Name
		{
			get
			{
				return this._Sales_District_Name;
			}
			set
			{
				if ((this._Sales_District_Name != value))
				{
					this.OnSales_District_NameChanging(value);
					this.SendPropertyChanging();
					this._Sales_District_Name = value;
					this.SendPropertyChanged("Sales_District_Name");
					this.OnSales_District_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SalesDistrict1_SalesDistrict2", Storage="_SalesDistrict2s", ThisKey="SalesDistrict1Id", OtherKey="SalesDistrict1Id")]
		public EntitySet<SalesDistrict2> SalesDistrict2s
		{
			get
			{
				return this._SalesDistrict2s;
			}
			set
			{
				this._SalesDistrict2s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SalesDistrict2s(SalesDistrict2 entity)
		{
			this.SendPropertyChanging();
			entity.SalesDistrict1 = this;
		}
		
		private void detach_SalesDistrict2s(SalesDistrict2 entity)
		{
			this.SendPropertyChanging();
			entity.SalesDistrict1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppDashboardSchema_LUE")]
	public partial class vAppDashboardSchema_LUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DashboardSchemaId;
		
		private string _DashboardSchemaName;
		
		private System.Nullable<int> _UserIn;
		
		private System.Nullable<System.DateTime> _DateIn;
		
		private string _RealName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDashboardSchemaIdChanging(int value);
    partial void OnDashboardSchemaIdChanged();
    partial void OnDashboardSchemaNameChanging(string value);
    partial void OnDashboardSchemaNameChanged();
    partial void OnUserInChanging(System.Nullable<int> value);
    partial void OnUserInChanged();
    partial void OnDateInChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    #endregion
		
		public vAppDashboardSchema_LUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DashboardSchemaId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DashboardSchemaId
		{
			get
			{
				return this._DashboardSchemaId;
			}
			set
			{
				if ((this._DashboardSchemaId != value))
				{
					this.OnDashboardSchemaIdChanging(value);
					this.SendPropertyChanging();
					this._DashboardSchemaId = value;
					this.SendPropertyChanged("DashboardSchemaId");
					this.OnDashboardSchemaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DashboardSchemaName", DbType="NVarChar(50)")]
		public string DashboardSchemaName
		{
			get
			{
				return this._DashboardSchemaName;
			}
			set
			{
				if ((this._DashboardSchemaName != value))
				{
					this.OnDashboardSchemaNameChanging(value);
					this.SendPropertyChanging();
					this._DashboardSchemaName = value;
					this.SendPropertyChanged("DashboardSchemaName");
					this.OnDashboardSchemaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIn", DbType="Int")]
		public System.Nullable<int> UserIn
		{
			get
			{
				return this._UserIn;
			}
			set
			{
				if ((this._UserIn != value))
				{
					this.OnUserInChanging(value);
					this.SendPropertyChanging();
					this._UserIn = value;
					this.SendPropertyChanged("UserIn");
					this.OnUserInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this.OnDateInChanging(value);
					this.SendPropertyChanging();
					this._DateIn = value;
					this.SendPropertyChanged("DateIn");
					this.OnDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppDatasourceParam_LUE")]
	public partial class vAppDatasourceParam_LUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AppDatasourceParamID;
		
		private System.Nullable<int> _DatasourceID;
		
		private string _ParamName;
		
		private string _ParamDisplayName;
		
		private System.Nullable<int> _UserIn;
		
		private System.Nullable<System.DateTime> _DateIn;
		
		private string _RealName;
		
		private string _DatasourceName;
		
		private string _DatasourceSPName;
		
		private string _AppDatasourceTypeName;
		
		private string _Desc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAppDatasourceParamIDChanging(int value);
    partial void OnAppDatasourceParamIDChanged();
    partial void OnDatasourceIDChanging(System.Nullable<int> value);
    partial void OnDatasourceIDChanged();
    partial void OnParamNameChanging(string value);
    partial void OnParamNameChanged();
    partial void OnParamDisplayNameChanging(string value);
    partial void OnParamDisplayNameChanged();
    partial void OnUserInChanging(System.Nullable<int> value);
    partial void OnUserInChanged();
    partial void OnDateInChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnDatasourceNameChanging(string value);
    partial void OnDatasourceNameChanged();
    partial void OnDatasourceSPNameChanging(string value);
    partial void OnDatasourceSPNameChanged();
    partial void OnAppDatasourceTypeNameChanging(string value);
    partial void OnAppDatasourceTypeNameChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    #endregion
		
		public vAppDatasourceParam_LUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceParamID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AppDatasourceParamID
		{
			get
			{
				return this._AppDatasourceParamID;
			}
			set
			{
				if ((this._AppDatasourceParamID != value))
				{
					this.OnAppDatasourceParamIDChanging(value);
					this.SendPropertyChanging();
					this._AppDatasourceParamID = value;
					this.SendPropertyChanged("AppDatasourceParamID");
					this.OnAppDatasourceParamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceID", DbType="Int")]
		public System.Nullable<int> DatasourceID
		{
			get
			{
				return this._DatasourceID;
			}
			set
			{
				if ((this._DatasourceID != value))
				{
					this.OnDatasourceIDChanging(value);
					this.SendPropertyChanging();
					this._DatasourceID = value;
					this.SendPropertyChanged("DatasourceID");
					this.OnDatasourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParamName", DbType="NVarChar(50)")]
		public string ParamName
		{
			get
			{
				return this._ParamName;
			}
			set
			{
				if ((this._ParamName != value))
				{
					this.OnParamNameChanging(value);
					this.SendPropertyChanging();
					this._ParamName = value;
					this.SendPropertyChanged("ParamName");
					this.OnParamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParamDisplayName", DbType="NVarChar(50)")]
		public string ParamDisplayName
		{
			get
			{
				return this._ParamDisplayName;
			}
			set
			{
				if ((this._ParamDisplayName != value))
				{
					this.OnParamDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._ParamDisplayName = value;
					this.SendPropertyChanged("ParamDisplayName");
					this.OnParamDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIn", DbType="Int")]
		public System.Nullable<int> UserIn
		{
			get
			{
				return this._UserIn;
			}
			set
			{
				if ((this._UserIn != value))
				{
					this.OnUserInChanging(value);
					this.SendPropertyChanging();
					this._UserIn = value;
					this.SendPropertyChanged("UserIn");
					this.OnUserInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this.OnDateInChanging(value);
					this.SendPropertyChanging();
					this._DateIn = value;
					this.SendPropertyChanged("DateIn");
					this.OnDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceName", DbType="NVarChar(50)")]
		public string DatasourceName
		{
			get
			{
				return this._DatasourceName;
			}
			set
			{
				if ((this._DatasourceName != value))
				{
					this.OnDatasourceNameChanging(value);
					this.SendPropertyChanging();
					this._DatasourceName = value;
					this.SendPropertyChanged("DatasourceName");
					this.OnDatasourceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceSPName", DbType="NVarChar(50)")]
		public string DatasourceSPName
		{
			get
			{
				return this._DatasourceSPName;
			}
			set
			{
				if ((this._DatasourceSPName != value))
				{
					this.OnDatasourceSPNameChanging(value);
					this.SendPropertyChanging();
					this._DatasourceSPName = value;
					this.SendPropertyChanged("DatasourceSPName");
					this.OnDatasourceSPNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeName", DbType="NVarChar(50)")]
		public string AppDatasourceTypeName
		{
			get
			{
				return this._AppDatasourceTypeName;
			}
			set
			{
				if ((this._AppDatasourceTypeName != value))
				{
					this.OnAppDatasourceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._AppDatasourceTypeName = value;
					this.SendPropertyChanged("AppDatasourceTypeName");
					this.OnAppDatasourceTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(255)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppDatasourceLayout_LUE")]
	public partial class vAppDatasourceLayout_LUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DatasourceLayoutId;
		
		private System.Nullable<int> _DatasourceID;
		
		private string _DatasourceLayoutName;
		
		private System.Nullable<int> _UserIn;
		
		private System.Nullable<System.DateTime> _DateIn;
		
		private string _RealName;
		
		private string _DatasourceName;
		
		private string _DatasourceSPName;
		
		private string _AppDatasourceTypeName;
		
		private string _Desc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDatasourceLayoutIdChanging(int value);
    partial void OnDatasourceLayoutIdChanged();
    partial void OnDatasourceIDChanging(System.Nullable<int> value);
    partial void OnDatasourceIDChanged();
    partial void OnDatasourceLayoutNameChanging(string value);
    partial void OnDatasourceLayoutNameChanged();
    partial void OnUserInChanging(System.Nullable<int> value);
    partial void OnUserInChanged();
    partial void OnDateInChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnDatasourceNameChanging(string value);
    partial void OnDatasourceNameChanged();
    partial void OnDatasourceSPNameChanging(string value);
    partial void OnDatasourceSPNameChanged();
    partial void OnAppDatasourceTypeNameChanging(string value);
    partial void OnAppDatasourceTypeNameChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    #endregion
		
		public vAppDatasourceLayout_LUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceLayoutId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DatasourceLayoutId
		{
			get
			{
				return this._DatasourceLayoutId;
			}
			set
			{
				if ((this._DatasourceLayoutId != value))
				{
					this.OnDatasourceLayoutIdChanging(value);
					this.SendPropertyChanging();
					this._DatasourceLayoutId = value;
					this.SendPropertyChanged("DatasourceLayoutId");
					this.OnDatasourceLayoutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceID", DbType="Int")]
		public System.Nullable<int> DatasourceID
		{
			get
			{
				return this._DatasourceID;
			}
			set
			{
				if ((this._DatasourceID != value))
				{
					this.OnDatasourceIDChanging(value);
					this.SendPropertyChanging();
					this._DatasourceID = value;
					this.SendPropertyChanged("DatasourceID");
					this.OnDatasourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceLayoutName", DbType="NVarChar(50)")]
		public string DatasourceLayoutName
		{
			get
			{
				return this._DatasourceLayoutName;
			}
			set
			{
				if ((this._DatasourceLayoutName != value))
				{
					this.OnDatasourceLayoutNameChanging(value);
					this.SendPropertyChanging();
					this._DatasourceLayoutName = value;
					this.SendPropertyChanged("DatasourceLayoutName");
					this.OnDatasourceLayoutNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIn", DbType="Int")]
		public System.Nullable<int> UserIn
		{
			get
			{
				return this._UserIn;
			}
			set
			{
				if ((this._UserIn != value))
				{
					this.OnUserInChanging(value);
					this.SendPropertyChanging();
					this._UserIn = value;
					this.SendPropertyChanged("UserIn");
					this.OnUserInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this.OnDateInChanging(value);
					this.SendPropertyChanging();
					this._DateIn = value;
					this.SendPropertyChanged("DateIn");
					this.OnDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceName", DbType="NVarChar(50)")]
		public string DatasourceName
		{
			get
			{
				return this._DatasourceName;
			}
			set
			{
				if ((this._DatasourceName != value))
				{
					this.OnDatasourceNameChanging(value);
					this.SendPropertyChanging();
					this._DatasourceName = value;
					this.SendPropertyChanged("DatasourceName");
					this.OnDatasourceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceSPName", DbType="NVarChar(50)")]
		public string DatasourceSPName
		{
			get
			{
				return this._DatasourceSPName;
			}
			set
			{
				if ((this._DatasourceSPName != value))
				{
					this.OnDatasourceSPNameChanging(value);
					this.SendPropertyChanging();
					this._DatasourceSPName = value;
					this.SendPropertyChanged("DatasourceSPName");
					this.OnDatasourceSPNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeName", DbType="NVarChar(50)")]
		public string AppDatasourceTypeName
		{
			get
			{
				return this._AppDatasourceTypeName;
			}
			set
			{
				if ((this._AppDatasourceTypeName != value))
				{
					this.OnAppDatasourceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._AppDatasourceTypeName = value;
					this.SendPropertyChanged("AppDatasourceTypeName");
					this.OnAppDatasourceTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(255)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppDatasourceType")]
	public partial class AppDatasourceType_LUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AppDatasourceTypeId;
		
		private string _AppDatasourceTypeName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAppDatasourceTypeIdChanging(int value);
    partial void OnAppDatasourceTypeIdChanged();
    partial void OnAppDatasourceTypeNameChanging(string value);
    partial void OnAppDatasourceTypeNameChanged();
    #endregion
		
		public AppDatasourceType_LUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AppDatasourceTypeId
		{
			get
			{
				return this._AppDatasourceTypeId;
			}
			set
			{
				if ((this._AppDatasourceTypeId != value))
				{
					this.OnAppDatasourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._AppDatasourceTypeId = value;
					this.SendPropertyChanged("AppDatasourceTypeId");
					this.OnAppDatasourceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeName", DbType="NVarChar(50)")]
		public string AppDatasourceTypeName
		{
			get
			{
				return this._AppDatasourceTypeName;
			}
			set
			{
				if ((this._AppDatasourceTypeName != value))
				{
					this.OnAppDatasourceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._AppDatasourceTypeName = value;
					this.SendPropertyChanged("AppDatasourceTypeName");
					this.OnAppDatasourceTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppDSCategory")]
	public partial class vAppDSCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DSCategoryId;
		
		private string _DSCategoryName;
		
		private string _DSCategoryDesc;
		
		private System.Nullable<int> _DSCategoryParent;
		
		private string _DSCategoryParentName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDSCategoryIdChanging(int value);
    partial void OnDSCategoryIdChanged();
    partial void OnDSCategoryNameChanging(string value);
    partial void OnDSCategoryNameChanged();
    partial void OnDSCategoryDescChanging(string value);
    partial void OnDSCategoryDescChanged();
    partial void OnDSCategoryParentChanging(System.Nullable<int> value);
    partial void OnDSCategoryParentChanged();
    partial void OnDSCategoryParentNameChanging(string value);
    partial void OnDSCategoryParentNameChanged();
    #endregion
		
		public vAppDSCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DSCategoryId
		{
			get
			{
				return this._DSCategoryId;
			}
			set
			{
				if ((this._DSCategoryId != value))
				{
					this.OnDSCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._DSCategoryId = value;
					this.SendPropertyChanged("DSCategoryId");
					this.OnDSCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryName", DbType="NVarChar(50)")]
		public string DSCategoryName
		{
			get
			{
				return this._DSCategoryName;
			}
			set
			{
				if ((this._DSCategoryName != value))
				{
					this.OnDSCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._DSCategoryName = value;
					this.SendPropertyChanged("DSCategoryName");
					this.OnDSCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryDesc", DbType="NVarChar(255)")]
		public string DSCategoryDesc
		{
			get
			{
				return this._DSCategoryDesc;
			}
			set
			{
				if ((this._DSCategoryDesc != value))
				{
					this.OnDSCategoryDescChanging(value);
					this.SendPropertyChanging();
					this._DSCategoryDesc = value;
					this.SendPropertyChanged("DSCategoryDesc");
					this.OnDSCategoryDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryParent", DbType="Int")]
		public System.Nullable<int> DSCategoryParent
		{
			get
			{
				return this._DSCategoryParent;
			}
			set
			{
				if ((this._DSCategoryParent != value))
				{
					this.OnDSCategoryParentChanging(value);
					this.SendPropertyChanging();
					this._DSCategoryParent = value;
					this.SendPropertyChanged("DSCategoryParent");
					this.OnDSCategoryParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryParentName", DbType="NVarChar(50)")]
		public string DSCategoryParentName
		{
			get
			{
				return this._DSCategoryParentName;
			}
			set
			{
				if ((this._DSCategoryParentName != value))
				{
					this.OnDSCategoryParentNameChanging(value);
					this.SendPropertyChanging();
					this._DSCategoryParentName = value;
					this.SendPropertyChanged("DSCategoryParentName");
					this.OnDSCategoryParentNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRD_BaseProduct")]
	public partial class PRD_BaseProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _BaseProductId;
		
		private string _BaseProduct;
		
		private System.Nullable<short> _BaseProductLevel;
		
		private System.Nullable<short> _BaseGroupId;
		
		private string _Group1;
		
		private string _Group2;
		
		private string _Group3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBaseProductIdChanging(short value);
    partial void OnBaseProductIdChanged();
    partial void OnBaseProductChanging(string value);
    partial void OnBaseProductChanged();
    partial void OnBaseProductLevelChanging(System.Nullable<short> value);
    partial void OnBaseProductLevelChanged();
    partial void OnBaseGroupIdChanging(System.Nullable<short> value);
    partial void OnBaseGroupIdChanged();
    partial void OnGroup1Changing(string value);
    partial void OnGroup1Changed();
    partial void OnGroup2Changing(string value);
    partial void OnGroup2Changed();
    partial void OnGroup3Changing(string value);
    partial void OnGroup3Changed();
    #endregion
		
		public PRD_BaseProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseProductId", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short BaseProductId
		{
			get
			{
				return this._BaseProductId;
			}
			set
			{
				if ((this._BaseProductId != value))
				{
					this.OnBaseProductIdChanging(value);
					this.SendPropertyChanging();
					this._BaseProductId = value;
					this.SendPropertyChanged("BaseProductId");
					this.OnBaseProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseProduct", DbType="NVarChar(50)")]
		public string BaseProduct
		{
			get
			{
				return this._BaseProduct;
			}
			set
			{
				if ((this._BaseProduct != value))
				{
					this.OnBaseProductChanging(value);
					this.SendPropertyChanging();
					this._BaseProduct = value;
					this.SendPropertyChanged("BaseProduct");
					this.OnBaseProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseProductLevel", DbType="SmallInt")]
		public System.Nullable<short> BaseProductLevel
		{
			get
			{
				return this._BaseProductLevel;
			}
			set
			{
				if ((this._BaseProductLevel != value))
				{
					this.OnBaseProductLevelChanging(value);
					this.SendPropertyChanging();
					this._BaseProductLevel = value;
					this.SendPropertyChanged("BaseProductLevel");
					this.OnBaseProductLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseGroupId", DbType="SmallInt")]
		public System.Nullable<short> BaseGroupId
		{
			get
			{
				return this._BaseGroupId;
			}
			set
			{
				if ((this._BaseGroupId != value))
				{
					this.OnBaseGroupIdChanging(value);
					this.SendPropertyChanging();
					this._BaseGroupId = value;
					this.SendPropertyChanged("BaseGroupId");
					this.OnBaseGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group1", DbType="NVarChar(50)")]
		public string Group1
		{
			get
			{
				return this._Group1;
			}
			set
			{
				if ((this._Group1 != value))
				{
					this.OnGroup1Changing(value);
					this.SendPropertyChanging();
					this._Group1 = value;
					this.SendPropertyChanged("Group1");
					this.OnGroup1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group2", DbType="NVarChar(50)")]
		public string Group2
		{
			get
			{
				return this._Group2;
			}
			set
			{
				if ((this._Group2 != value))
				{
					this.OnGroup2Changing(value);
					this.SendPropertyChanging();
					this._Group2 = value;
					this.SendPropertyChanged("Group2");
					this.OnGroup2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group3", DbType="NVarChar(50)")]
		public string Group3
		{
			get
			{
				return this._Group3;
			}
			set
			{
				if ((this._Group3 != value))
				{
					this.OnGroup3Changing(value);
					this.SendPropertyChanging();
					this._Group3 = value;
					this.SendPropertyChanged("Group3");
					this.OnGroup3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppDatasource_LUE")]
	public partial class vAppDatasource_LUE
	{
		
		private int _DatasourceID;
		
		private System.Nullable<int> _AppDatasourceTypeId;
		
		private string _DatasourceName;
		
		private string _DatasourceSPName;
		
		private System.Nullable<int> _UserIn;
		
		private System.Nullable<System.DateTime> _DateIn;
		
		private string _RealName;
		
		private string _AppDatasourceTypeName;
		
		private System.Nullable<int> _DSCategoryId;
		
		private string _DSCategoryName;
		
		private string _DSCategoryDesc;
		
		public vAppDatasource_LUE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceID", DbType="Int NOT NULL")]
		public int DatasourceID
		{
			get
			{
				return this._DatasourceID;
			}
			set
			{
				if ((this._DatasourceID != value))
				{
					this._DatasourceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeId", DbType="Int")]
		public System.Nullable<int> AppDatasourceTypeId
		{
			get
			{
				return this._AppDatasourceTypeId;
			}
			set
			{
				if ((this._AppDatasourceTypeId != value))
				{
					this._AppDatasourceTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceName", DbType="NVarChar(50)")]
		public string DatasourceName
		{
			get
			{
				return this._DatasourceName;
			}
			set
			{
				if ((this._DatasourceName != value))
				{
					this._DatasourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatasourceSPName", DbType="NVarChar(50)")]
		public string DatasourceSPName
		{
			get
			{
				return this._DatasourceSPName;
			}
			set
			{
				if ((this._DatasourceSPName != value))
				{
					this._DatasourceSPName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIn", DbType="Int")]
		public System.Nullable<int> UserIn
		{
			get
			{
				return this._UserIn;
			}
			set
			{
				if ((this._UserIn != value))
				{
					this._UserIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this._DateIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDatasourceTypeName", DbType="NVarChar(50)")]
		public string AppDatasourceTypeName
		{
			get
			{
				return this._AppDatasourceTypeName;
			}
			set
			{
				if ((this._AppDatasourceTypeName != value))
				{
					this._AppDatasourceTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryId", DbType="Int")]
		public System.Nullable<int> DSCategoryId
		{
			get
			{
				return this._DSCategoryId;
			}
			set
			{
				if ((this._DSCategoryId != value))
				{
					this._DSCategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryName", DbType="NVarChar(50)")]
		public string DSCategoryName
		{
			get
			{
				return this._DSCategoryName;
			}
			set
			{
				if ((this._DSCategoryName != value))
				{
					this._DSCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCategoryDesc", DbType="NVarChar(255)")]
		public string DSCategoryDesc
		{
			get
			{
				return this._DSCategoryDesc;
			}
			set
			{
				if ((this._DSCategoryDesc != value))
				{
					this._DSCategoryDesc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAppProductDetails")]
	public partial class vAppProductDetail
	{
		
		private double _Material_Number;
		
		private string _Material_Name;
		
		private string _BaseProduct;
		
		private string _BaseGroup;
		
		public vAppProductDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Number]", Storage="_Material_Number", DbType="Float NOT NULL")]
		public double Material_Number
		{
			get
			{
				return this._Material_Number;
			}
			set
			{
				if ((this._Material_Number != value))
				{
					this._Material_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Name]", Storage="_Material_Name", DbType="NVarChar(255)")]
		public string Material_Name
		{
			get
			{
				return this._Material_Name;
			}
			set
			{
				if ((this._Material_Name != value))
				{
					this._Material_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseProduct", DbType="NVarChar(50)")]
		public string BaseProduct
		{
			get
			{
				return this._BaseProduct;
			}
			set
			{
				if ((this._BaseProduct != value))
				{
					this._BaseProduct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseGroup", DbType="NVarChar(50)")]
		public string BaseGroup
		{
			get
			{
				return this._BaseGroup;
			}
			set
			{
				if ((this._BaseGroup != value))
				{
					this._BaseGroup = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
