#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NICSQLTools.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IC_DB")]
	public partial class dsLinqDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dsLinqDataDataContext() : 
				base(global::NICSQLTools.Properties.Settings.Default.IC_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_0_0_Final_Data_All> _0_0_Final_Data_Alls
		{
			get
			{
				return this.GetTable<_0_0_Final_Data_All>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[0-0 Final Data All]")]
	public partial class _0_0_Final_Data_All
	{
		
		private string _Billing_Document;
		
		private System.Nullable<double> _Volume_14;
		
		private System.Nullable<double> _Volume_13;
		
		private System.Nullable<double> _Value_14;
		
		private System.Nullable<double> _Value_13;
		
		private System.Nullable<double> _Cases_14;
		
		private System.Nullable<double> _Cases_13;
		
		private string _Type;
		
		private string _Material_Name;
		
		private string _Base_Base_Product;
		
		private string _Brand;
		
		private string _Name_3_Ar;
		
		private string _Customer_Type_2;
		
		private string _Customer_Type;
		
		private string _Name_3_En;
		
		private string _Brand_Route;
		
		private string _Supervisor;
		
		private string _ASM;
		
		private string _Sales_District_Name;
		
		private string _Route_Name;
		
		private string _Day_Month;
		
		private string _Month;
		
		private string _yeard;
		
		private string _Route___Sold;
		
		private System.Nullable<int> _Material_Number;
		
		private System.Nullable<System.DateTime> _Billing_date_for_bil;
		
		private string _Sold_to_party;
		
		private string _Distribution_Channel;
		
		private string _Base_New;
		
		private string _Level_CCSD;
		
		private string _FRZ_brand;
		
		private string _Sales_District_2;
		
		private long _AutoKey;
		
		public _0_0_Final_Data_All()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing Document]", Storage="_Billing_Document", DbType="NVarChar(255)")]
		public string Billing_Document
		{
			get
			{
				return this._Billing_Document;
			}
			set
			{
				if ((this._Billing_Document != value))
				{
					this._Billing_Document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Volume 14]", Storage="_Volume_14", DbType="Float")]
		public System.Nullable<double> Volume_14
		{
			get
			{
				return this._Volume_14;
			}
			set
			{
				if ((this._Volume_14 != value))
				{
					this._Volume_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Volume 13]", Storage="_Volume_13", DbType="Float")]
		public System.Nullable<double> Volume_13
		{
			get
			{
				return this._Volume_13;
			}
			set
			{
				if ((this._Volume_13 != value))
				{
					this._Volume_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 14]", Storage="_Value_14", DbType="Float")]
		public System.Nullable<double> Value_14
		{
			get
			{
				return this._Value_14;
			}
			set
			{
				if ((this._Value_14 != value))
				{
					this._Value_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Value 13]", Storage="_Value_13", DbType="Float")]
		public System.Nullable<double> Value_13
		{
			get
			{
				return this._Value_13;
			}
			set
			{
				if ((this._Value_13 != value))
				{
					this._Value_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 14]", Storage="_Cases_14", DbType="Float")]
		public System.Nullable<double> Cases_14
		{
			get
			{
				return this._Cases_14;
			}
			set
			{
				if ((this._Cases_14 != value))
				{
					this._Cases_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cases 13]", Storage="_Cases_13", DbType="Float")]
		public System.Nullable<double> Cases_13
		{
			get
			{
				return this._Cases_13;
			}
			set
			{
				if ((this._Cases_13 != value))
				{
					this._Cases_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Name]", Storage="_Material_Name", DbType="NVarChar(255)")]
		public string Material_Name
		{
			get
			{
				return this._Material_Name;
			}
			set
			{
				if ((this._Material_Name != value))
				{
					this._Material_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Base Product]", Storage="_Base_Base_Product", DbType="NVarChar(255)")]
		public string Base_Base_Product
		{
			get
			{
				return this._Base_Base_Product;
			}
			set
			{
				if ((this._Base_Base_Product != value))
				{
					this._Base_Base_Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="NVarChar(255)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 3 Ar]", Storage="_Name_3_Ar", DbType="NVarChar(255)")]
		public string Name_3_Ar
		{
			get
			{
				return this._Name_3_Ar;
			}
			set
			{
				if ((this._Name_3_Ar != value))
				{
					this._Name_3_Ar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Type 2]", Storage="_Customer_Type_2", DbType="NVarChar(255)")]
		public string Customer_Type_2
		{
			get
			{
				return this._Customer_Type_2;
			}
			set
			{
				if ((this._Customer_Type_2 != value))
				{
					this._Customer_Type_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Type]", Storage="_Customer_Type", DbType="NVarChar(255)")]
		public string Customer_Type
		{
			get
			{
				return this._Customer_Type;
			}
			set
			{
				if ((this._Customer_Type != value))
				{
					this._Customer_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Name 3 En]", Storage="_Name_3_En", DbType="NVarChar(255)")]
		public string Name_3_En
		{
			get
			{
				return this._Name_3_En;
			}
			set
			{
				if ((this._Name_3_En != value))
				{
					this._Name_3_En = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Brand Route]", Storage="_Brand_Route", DbType="NVarChar(255)")]
		public string Brand_Route
		{
			get
			{
				return this._Brand_Route;
			}
			set
			{
				if ((this._Brand_Route != value))
				{
					this._Brand_Route = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="NVarChar(255)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this._Supervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASM", DbType="NVarChar(255)")]
		public string ASM
		{
			get
			{
				return this._ASM;
			}
			set
			{
				if ((this._ASM != value))
				{
					this._ASM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District Name]", Storage="_Sales_District_Name", DbType="NVarChar(255)")]
		public string Sales_District_Name
		{
			get
			{
				return this._Sales_District_Name;
			}
			set
			{
				if ((this._Sales_District_Name != value))
				{
					this._Sales_District_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Route Name]", Storage="_Route_Name", DbType="NVarChar(255)")]
		public string Route_Name
		{
			get
			{
				return this._Route_Name;
			}
			set
			{
				if ((this._Route_Name != value))
				{
					this._Route_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Day-Month]", Storage="_Day_Month", DbType="NVarChar(255)")]
		public string Day_Month
		{
			get
			{
				return this._Day_Month;
			}
			set
			{
				if ((this._Day_Month != value))
				{
					this._Day_Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(255)")]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeard", DbType="NVarChar(50)")]
		public string yeard
		{
			get
			{
				return this._yeard;
			}
			set
			{
				if ((this._yeard != value))
				{
					this._yeard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Route & Sold]", Storage="_Route___Sold", DbType="NVarChar(50)")]
		public string Route___Sold
		{
			get
			{
				return this._Route___Sold;
			}
			set
			{
				if ((this._Route___Sold != value))
				{
					this._Route___Sold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Material Number]", Storage="_Material_Number", DbType="Int")]
		public System.Nullable<int> Material_Number
		{
			get
			{
				return this._Material_Number;
			}
			set
			{
				if ((this._Material_Number != value))
				{
					this._Material_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Billing date for bil]", Storage="_Billing_date_for_bil", DbType="DateTime")]
		public System.Nullable<System.DateTime> Billing_date_for_bil
		{
			get
			{
				return this._Billing_date_for_bil;
			}
			set
			{
				if ((this._Billing_date_for_bil != value))
				{
					this._Billing_date_for_bil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sold-to party]", Storage="_Sold_to_party", DbType="NVarChar(255)")]
		public string Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this._Sold_to_party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Distribution Channel]", Storage="_Distribution_Channel", DbType="NVarChar(255)")]
		public string Distribution_Channel
		{
			get
			{
				return this._Distribution_Channel;
			}
			set
			{
				if ((this._Distribution_Channel != value))
				{
					this._Distribution_Channel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base-New]", Storage="_Base_New", DbType="NVarChar(255)")]
		public string Base_New
		{
			get
			{
				return this._Base_New;
			}
			set
			{
				if ((this._Base_New != value))
				{
					this._Base_New = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level CCSD]", Storage="_Level_CCSD", DbType="NVarChar(255)")]
		public string Level_CCSD
		{
			get
			{
				return this._Level_CCSD;
			}
			set
			{
				if ((this._Level_CCSD != value))
				{
					this._Level_CCSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FRZ brand]", Storage="_FRZ_brand", DbType="NVarChar(255)")]
		public string FRZ_brand
		{
			get
			{
				return this._FRZ_brand;
			}
			set
			{
				if ((this._FRZ_brand != value))
				{
					this._FRZ_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sales District 2]", Storage="_Sales_District_2", DbType="NVarChar(255)")]
		public string Sales_District_2
		{
			get
			{
				return this._Sales_District_2;
			}
			set
			{
				if ((this._Sales_District_2 != value))
				{
					this._Sales_District_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", DbType="BigInt NOT NULL")]
		public long AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this._AutoKey = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
