//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NICSQLTools.Data.IC_DB
{

    [NonPersistent]
    public partial class sp_App_01C_Cus_RouteResult
    {
        public string Route { get; set; }
        public string Customer { get; set; }
        public int Fri { get; set; }
        public int Sat { get; set; }
        public int Sun { get; set; }
        public int Mon { get; set; }
        public int Tus { get; set; }
        public int Wen { get; set; }
        public int Thr { get; set; }
        public DateTime ValidFrom { get; set; }
        public short MonthNum { get; set; }
        public short YearNum { get; set; }
        public string RouteName { get; set; }
        public string ASM { get; set; }
        public string Supervisor { get; set; }
        public string BrandRoute { get; set; }
        public string SalesDistrict2 { get; set; }
    }

}
